/****************************************************************************
**
** Metadata for MMVARILib generated by dumpcpp v5.15.2 using
** C:\Qt\5.15.2\mingw81_32\bin\dumpcpp.exe MMVARI.ocx
** from the type library MMVARI.ocx
**
****************************************************************************/

#define QAX_DUMPCPP_MMVARILIB_NOINLINES
#include "mmvarilib.h"
#include <OAIdl.h>

using namespace MMVARILib;

struct qt_meta_stringdata_all_t {
    QByteArrayData data[416];
    char stringdata0[4791];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 19, 0),
QT_MOC_LITERAL(1, 20, 9, 0),
QT_MOC_LITERAL(2, 30, 0, 0),
QT_MOC_LITERAL(3, 31, 4, 0),
QT_MOC_LITERAL(4, 36, 6, 0),
QT_MOC_LITERAL(5, 43, 4, 0),
QT_MOC_LITERAL(6, 48, 4, 0),
QT_MOC_LITERAL(7, 53, 15, 0),
QT_MOC_LITERAL(8, 69, 4, 0),
QT_MOC_LITERAL(9, 74, 6, 0),
QT_MOC_LITERAL(10, 81, 4, 0),
QT_MOC_LITERAL(11, 86, 4, 0),
QT_MOC_LITERAL(12, 91, 8, 0),
QT_MOC_LITERAL(13, 100, 12, 0),
QT_MOC_LITERAL(14, 113, 5, 0),
QT_MOC_LITERAL(15, 119, 11, 0),
QT_MOC_LITERAL(16, 131, 6, 0),
QT_MOC_LITERAL(17, 138, 15, 0),
QT_MOC_LITERAL(18, 154, 4, 0),
QT_MOC_LITERAL(19, 159, 5, 0),
QT_MOC_LITERAL(20, 165, 4, 0),
QT_MOC_LITERAL(21, 170, 5, 0),
QT_MOC_LITERAL(22, 176, 24, 0),
QT_MOC_LITERAL(23, 201, 7, 0),
QT_MOC_LITERAL(24, 209, 4, 0),
QT_MOC_LITERAL(25, 214, 6, 0),
QT_MOC_LITERAL(26, 221, 8, 0),
QT_MOC_LITERAL(27, 230, 18, 0),
QT_MOC_LITERAL(28, 249, 5, 0),
QT_MOC_LITERAL(29, 255, 6, 0),
QT_MOC_LITERAL(30, 262, 24, 0),
QT_MOC_LITERAL(31, 287, 9, 0),
QT_MOC_LITERAL(32, 297, 3, 0),
QT_MOC_LITERAL(33, 301, 22, 0),
QT_MOC_LITERAL(34, 324, 5, 0),
QT_MOC_LITERAL(35, 330, 6, 0),
QT_MOC_LITERAL(36, 337, 6, 0),
QT_MOC_LITERAL(37, 344, 18, 0),
QT_MOC_LITERAL(38, 363, 7, 0),
QT_MOC_LITERAL(39, 371, 18, 0),
QT_MOC_LITERAL(40, 390, 11, 0),
QT_MOC_LITERAL(41, 402, 6, 0),
QT_MOC_LITERAL(42, 409, 13, 0),
QT_MOC_LITERAL(43, 423, 11, 0),
QT_MOC_LITERAL(44, 435, 11, 0),
QT_MOC_LITERAL(45, 447, 8, 0),
QT_MOC_LITERAL(46, 456, 4, 0),
QT_MOC_LITERAL(47, 461, 7, 0),
QT_MOC_LITERAL(48, 469, 6, 0),
QT_MOC_LITERAL(49, 476, 6, 0),
QT_MOC_LITERAL(50, 483, 8, 0),
QT_MOC_LITERAL(51, 492, 7, 0),
QT_MOC_LITERAL(52, 500, 8, 0),
QT_MOC_LITERAL(53, 509, 5, 0),
QT_MOC_LITERAL(54, 515, 8, 0),
QT_MOC_LITERAL(55, 524, 8, 0),
QT_MOC_LITERAL(56, 533, 14, 0),
QT_MOC_LITERAL(57, 548, 5, 0),
QT_MOC_LITERAL(58, 554, 13, 0),
QT_MOC_LITERAL(59, 568, 5, 0),
QT_MOC_LITERAL(60, 574, 4, 0),
QT_MOC_LITERAL(61, 579, 4, 0),
QT_MOC_LITERAL(62, 584, 11, 0),
QT_MOC_LITERAL(63, 596, 7, 0),
QT_MOC_LITERAL(64, 604, 10, 0),
QT_MOC_LITERAL(65, 615, 9, 0),
QT_MOC_LITERAL(66, 625, 5, 0),
QT_MOC_LITERAL(67, 631, 8, 0),
QT_MOC_LITERAL(68, 640, 10, 0),
QT_MOC_LITERAL(69, 651, 3, 0),
QT_MOC_LITERAL(70, 655, 5, 0),
QT_MOC_LITERAL(71, 661, 4, 0),
QT_MOC_LITERAL(72, 666, 12, 0),
QT_MOC_LITERAL(73, 679, 12, 0),
QT_MOC_LITERAL(74, 692, 10, 0),
QT_MOC_LITERAL(75, 703, 8, 0),
QT_MOC_LITERAL(76, 712, 7, 0),
QT_MOC_LITERAL(77, 720, 3, 0),
QT_MOC_LITERAL(78, 724, 7, 0),
QT_MOC_LITERAL(79, 732, 4, 0),
QT_MOC_LITERAL(80, 737, 10, 0),
QT_MOC_LITERAL(81, 748, 7, 0),
QT_MOC_LITERAL(82, 756, 14, 0),
QT_MOC_LITERAL(83, 771, 11, 0),
QT_MOC_LITERAL(84, 783, 13, 0),
QT_MOC_LITERAL(85, 797, 10, 0),
QT_MOC_LITERAL(86, 808, 10, 0),
QT_MOC_LITERAL(87, 819, 7, 0),
QT_MOC_LITERAL(88, 827, 13, 0),
QT_MOC_LITERAL(89, 841, 10, 0),
QT_MOC_LITERAL(90, 852, 16, 0),
QT_MOC_LITERAL(91, 869, 13, 0),
QT_MOC_LITERAL(92, 883, 7, 0),
QT_MOC_LITERAL(93, 891, 4, 0),
QT_MOC_LITERAL(94, 896, 16, 0),
QT_MOC_LITERAL(95, 913, 13, 0),
QT_MOC_LITERAL(96, 927, 16, 0),
QT_MOC_LITERAL(97, 944, 13, 0),
QT_MOC_LITERAL(98, 958, 7, 0),
QT_MOC_LITERAL(99, 966, 4, 0),
QT_MOC_LITERAL(100, 971, 9, 0),
QT_MOC_LITERAL(101, 981, 6, 0),
QT_MOC_LITERAL(102, 988, 12, 0),
QT_MOC_LITERAL(103, 1001, 11, 0),
QT_MOC_LITERAL(104, 1013, 8, 0),
QT_MOC_LITERAL(105, 1022, 12, 0),
QT_MOC_LITERAL(106, 1035, 9, 0),
QT_MOC_LITERAL(107, 1045, 11, 0),
QT_MOC_LITERAL(108, 1057, 9, 0),
QT_MOC_LITERAL(109, 1067, 6, 0),
QT_MOC_LITERAL(110, 1074, 13, 0),
QT_MOC_LITERAL(111, 1088, 18, 0),
QT_MOC_LITERAL(112, 1107, 15, 0),
QT_MOC_LITERAL(113, 1123, 6, 0),
QT_MOC_LITERAL(114, 1130, 3, 0),
QT_MOC_LITERAL(115, 1134, 19, 0),
QT_MOC_LITERAL(116, 1154, 16, 0),
QT_MOC_LITERAL(117, 1171, 7, 0),
QT_MOC_LITERAL(118, 1179, 22, 0),
QT_MOC_LITERAL(119, 1202, 19, 0),
QT_MOC_LITERAL(120, 1222, 19, 0),
QT_MOC_LITERAL(121, 1242, 16, 0),
QT_MOC_LITERAL(122, 1259, 13, 0),
QT_MOC_LITERAL(123, 1273, 16, 0),
QT_MOC_LITERAL(124, 1290, 11, 0),
QT_MOC_LITERAL(125, 1302, 14, 0),
QT_MOC_LITERAL(126, 1317, 11, 0),
QT_MOC_LITERAL(127, 1329, 13, 0),
QT_MOC_LITERAL(128, 1343, 10, 0),
QT_MOC_LITERAL(129, 1354, 8, 0),
QT_MOC_LITERAL(130, 1363, 5, 0),
QT_MOC_LITERAL(131, 1369, 11, 0),
QT_MOC_LITERAL(132, 1381, 8, 0),
QT_MOC_LITERAL(133, 1390, 15, 0),
QT_MOC_LITERAL(134, 1406, 12, 0),
QT_MOC_LITERAL(135, 1419, 7, 0),
QT_MOC_LITERAL(136, 1427, 4, 0),
QT_MOC_LITERAL(137, 1432, 7, 0),
QT_MOC_LITERAL(138, 1440, 4, 0),
QT_MOC_LITERAL(139, 1445, 14, 0),
QT_MOC_LITERAL(140, 1460, 11, 0),
QT_MOC_LITERAL(141, 1472, 16, 0),
QT_MOC_LITERAL(142, 1489, 13, 0),
QT_MOC_LITERAL(143, 1503, 13, 0),
QT_MOC_LITERAL(144, 1517, 10, 0),
QT_MOC_LITERAL(145, 1528, 13, 0),
QT_MOC_LITERAL(146, 1542, 10, 0),
QT_MOC_LITERAL(147, 1553, 16, 0),
QT_MOC_LITERAL(148, 1570, 13, 0),
QT_MOC_LITERAL(149, 1584, 10, 0),
QT_MOC_LITERAL(150, 1595, 13, 0),
QT_MOC_LITERAL(151, 1609, 10, 0),
QT_MOC_LITERAL(152, 1620, 13, 0),
QT_MOC_LITERAL(153, 1634, 10, 0),
QT_MOC_LITERAL(154, 1645, 13, 0),
QT_MOC_LITERAL(155, 1659, 10, 0),
QT_MOC_LITERAL(156, 1670, 12, 0),
QT_MOC_LITERAL(157, 1683, 9, 0),
QT_MOC_LITERAL(158, 1693, 12, 0),
QT_MOC_LITERAL(159, 1706, 9, 0),
QT_MOC_LITERAL(160, 1716, 15, 0),
QT_MOC_LITERAL(161, 1732, 12, 0),
QT_MOC_LITERAL(162, 1745, 13, 0),
QT_MOC_LITERAL(163, 1759, 10, 0),
QT_MOC_LITERAL(164, 1770, 11, 0),
QT_MOC_LITERAL(165, 1782, 8, 0),
QT_MOC_LITERAL(166, 1791, 12, 0),
QT_MOC_LITERAL(167, 1804, 9, 0),
QT_MOC_LITERAL(168, 1814, 11, 0),
QT_MOC_LITERAL(169, 1826, 15, 0),
QT_MOC_LITERAL(170, 1842, 12, 0),
QT_MOC_LITERAL(171, 1855, 18, 0),
QT_MOC_LITERAL(172, 1874, 15, 0),
QT_MOC_LITERAL(173, 1890, 14, 0),
QT_MOC_LITERAL(174, 1905, 11, 0),
QT_MOC_LITERAL(175, 1917, 11, 0),
QT_MOC_LITERAL(176, 1929, 8, 0),
QT_MOC_LITERAL(177, 1938, 12, 0),
QT_MOC_LITERAL(178, 1951, 9, 0),
QT_MOC_LITERAL(179, 1961, 8, 0),
QT_MOC_LITERAL(180, 1970, 5, 0),
QT_MOC_LITERAL(181, 1976, 11, 0),
QT_MOC_LITERAL(182, 1988, 8, 0),
QT_MOC_LITERAL(183, 1997, 8, 0),
QT_MOC_LITERAL(184, 2006, 11, 0),
QT_MOC_LITERAL(185, 2018, 8, 0),
QT_MOC_LITERAL(186, 2027, 13, 0),
QT_MOC_LITERAL(187, 2041, 10, 0),
QT_MOC_LITERAL(188, 2052, 13, 0),
QT_MOC_LITERAL(189, 2066, 10, 0),
QT_MOC_LITERAL(190, 2077, 11, 0),
QT_MOC_LITERAL(191, 2089, 14, 0),
QT_MOC_LITERAL(192, 2104, 11, 0),
QT_MOC_LITERAL(193, 2116, 13, 0),
QT_MOC_LITERAL(194, 2130, 11, 0),
QT_MOC_LITERAL(195, 2142, 11, 0),
QT_MOC_LITERAL(196, 2154, 8, 0),
QT_MOC_LITERAL(197, 2163, 15, 0),
QT_MOC_LITERAL(198, 2179, 12, 0),
QT_MOC_LITERAL(199, 2192, 15, 0),
QT_MOC_LITERAL(200, 2208, 12, 0),
QT_MOC_LITERAL(201, 2221, 13, 0),
QT_MOC_LITERAL(202, 2235, 10, 0),
QT_MOC_LITERAL(203, 2246, 11, 0),
QT_MOC_LITERAL(204, 2258, 8, 0),
QT_MOC_LITERAL(205, 2267, 11, 0),
QT_MOC_LITERAL(206, 2279, 8, 0),
QT_MOC_LITERAL(207, 2288, 7, 0),
QT_MOC_LITERAL(208, 2296, 11, 0),
QT_MOC_LITERAL(209, 2308, 8, 0),
QT_MOC_LITERAL(210, 2317, 11, 0),
QT_MOC_LITERAL(211, 2329, 6, 0),
QT_MOC_LITERAL(212, 2336, 5, 0),
QT_MOC_LITERAL(213, 2342, 8, 0),
QT_MOC_LITERAL(214, 2351, 10, 0),
QT_MOC_LITERAL(215, 2362, 9, 0),
QT_MOC_LITERAL(216, 2372, 3, 0),
QT_MOC_LITERAL(217, 2376, 8, 0),
QT_MOC_LITERAL(218, 2385, 7, 0),
QT_MOC_LITERAL(219, 2393, 16, 0),
QT_MOC_LITERAL(220, 2410, 11, 0),
QT_MOC_LITERAL(221, 2422, 11, 0),
QT_MOC_LITERAL(222, 2434, 11, 0),
QT_MOC_LITERAL(223, 2446, 14, 0),
QT_MOC_LITERAL(224, 2461, 9, 0),
QT_MOC_LITERAL(225, 2471, 11, 0),
QT_MOC_LITERAL(226, 2483, 11, 0),
QT_MOC_LITERAL(227, 2495, 14, 0),
QT_MOC_LITERAL(228, 2510, 12, 0),
QT_MOC_LITERAL(229, 2523, 13, 0),
QT_MOC_LITERAL(230, 2537, 10, 0),
QT_MOC_LITERAL(231, 2548, 10, 0),
QT_MOC_LITERAL(232, 2559, 10, 0),
QT_MOC_LITERAL(233, 2570, 10, 0),
QT_MOC_LITERAL(234, 2581, 7, 0),
QT_MOC_LITERAL(235, 2589, 7, 0),
QT_MOC_LITERAL(236, 2597, 10, 0),
QT_MOC_LITERAL(237, 2608, 7, 0),
QT_MOC_LITERAL(238, 2616, 9, 0),
QT_MOC_LITERAL(239, 2626, 12, 0),
QT_MOC_LITERAL(240, 2639, 9, 0),
QT_MOC_LITERAL(241, 2649, 9, 0),
QT_MOC_LITERAL(242, 2659, 12, 0),
QT_MOC_LITERAL(243, 2672, 11, 0),
QT_MOC_LITERAL(244, 2684, 11, 0),
QT_MOC_LITERAL(245, 2696, 13, 0),
QT_MOC_LITERAL(246, 2710, 11, 0),
QT_MOC_LITERAL(247, 2722, 13, 0),
QT_MOC_LITERAL(248, 2736, 12, 0),
QT_MOC_LITERAL(249, 2749, 15, 0),
QT_MOC_LITERAL(250, 2765, 18, 0),
QT_MOC_LITERAL(251, 2784, 17, 0),
QT_MOC_LITERAL(252, 2802, 17, 0),
QT_MOC_LITERAL(253, 2820, 14, 0),
QT_MOC_LITERAL(254, 2835, 13, 0),
QT_MOC_LITERAL(255, 2849, 9, 0),
QT_MOC_LITERAL(256, 2859, 10, 0),
QT_MOC_LITERAL(257, 2870, 7, 0),
QT_MOC_LITERAL(258, 2878, 7, 0),
QT_MOC_LITERAL(259, 2886, 7, 0),
QT_MOC_LITERAL(260, 2894, 10, 0),
QT_MOC_LITERAL(261, 2905, 11, 0),
QT_MOC_LITERAL(262, 2917, 6, 0),
QT_MOC_LITERAL(263, 2924, 6, 0),
QT_MOC_LITERAL(264, 2931, 5, 0),
QT_MOC_LITERAL(265, 2937, 5, 0),
QT_MOC_LITERAL(266, 2943, 3, 0),
QT_MOC_LITERAL(267, 2947, 10, 0),
QT_MOC_LITERAL(268, 2958, 5, 0),
QT_MOC_LITERAL(269, 2964, 11, 0),
QT_MOC_LITERAL(270, 2976, 8, 0),
QT_MOC_LITERAL(271, 2985, 7, 0),
QT_MOC_LITERAL(272, 2993, 7, 0),
QT_MOC_LITERAL(273, 3001, 8, 0),
QT_MOC_LITERAL(274, 3010, 8, 0),
QT_MOC_LITERAL(275, 3019, 5, 0),
QT_MOC_LITERAL(276, 3025, 11, 0),
QT_MOC_LITERAL(277, 3037, 9, 0),
QT_MOC_LITERAL(278, 3047, 6, 0),
QT_MOC_LITERAL(279, 3054, 20, 0),
QT_MOC_LITERAL(280, 3075, 11, 0),
QT_MOC_LITERAL(281, 3087, 13, 0),
QT_MOC_LITERAL(282, 3101, 4, 0),
QT_MOC_LITERAL(283, 3106, 10, 0),
QT_MOC_LITERAL(284, 3117, 7, 0),
QT_MOC_LITERAL(285, 3125, 10, 0),
QT_MOC_LITERAL(286, 3136, 7, 0),
QT_MOC_LITERAL(287, 3144, 12, 0),
QT_MOC_LITERAL(288, 3157, 9, 0),
QT_MOC_LITERAL(289, 3167, 7, 0),
QT_MOC_LITERAL(290, 3175, 8, 0),
QT_MOC_LITERAL(291, 3184, 5, 0),
QT_MOC_LITERAL(292, 3190, 12, 0),
QT_MOC_LITERAL(293, 3203, 9, 0),
QT_MOC_LITERAL(294, 3213, 10, 0),
QT_MOC_LITERAL(295, 3224, 7, 0),
QT_MOC_LITERAL(296, 3232, 10, 0),
QT_MOC_LITERAL(297, 3243, 7, 0),
QT_MOC_LITERAL(298, 3251, 18, 0),
QT_MOC_LITERAL(299, 3270, 15, 0),
QT_MOC_LITERAL(300, 3286, 14, 0),
QT_MOC_LITERAL(301, 3301, 14, 0),
QT_MOC_LITERAL(302, 3316, 20, 0),
QT_MOC_LITERAL(303, 3337, 18, 0),
QT_MOC_LITERAL(304, 3356, 11, 0),
QT_MOC_LITERAL(305, 3368, 5, 0),
QT_MOC_LITERAL(306, 3374, 4, 0),
QT_MOC_LITERAL(307, 3379, 10, 0),
QT_MOC_LITERAL(308, 3390, 4, 0),
QT_MOC_LITERAL(309, 3395, 3, 0),
QT_MOC_LITERAL(310, 3399, 5, 0),
QT_MOC_LITERAL(311, 3405, 12, 0),
QT_MOC_LITERAL(312, 3418, 9, 0),
QT_MOC_LITERAL(313, 3428, 14, 0),
QT_MOC_LITERAL(314, 3443, 12, 0),
QT_MOC_LITERAL(315, 3456, 9, 0),
QT_MOC_LITERAL(316, 3466, 11, 0),
QT_MOC_LITERAL(317, 3478, 8, 0),
QT_MOC_LITERAL(318, 3487, 11, 0),
QT_MOC_LITERAL(319, 3499, 8, 0),
QT_MOC_LITERAL(320, 3508, 10, 0),
QT_MOC_LITERAL(321, 3519, 7, 0),
QT_MOC_LITERAL(322, 3527, 12, 0),
QT_MOC_LITERAL(323, 3540, 9, 0),
QT_MOC_LITERAL(324, 3550, 10, 0),
QT_MOC_LITERAL(325, 3561, 7, 0),
QT_MOC_LITERAL(326, 3569, 14, 0),
QT_MOC_LITERAL(327, 3584, 11, 0),
QT_MOC_LITERAL(328, 3596, 18, 0),
QT_MOC_LITERAL(329, 3615, 15, 0),
QT_MOC_LITERAL(330, 3631, 12, 0),
QT_MOC_LITERAL(331, 3644, 5, 0),
QT_MOC_LITERAL(332, 3650, 12, 0),
QT_MOC_LITERAL(333, 3663, 10, 0),
QT_MOC_LITERAL(334, 3674, 12, 0),
QT_MOC_LITERAL(335, 3687, 12, 0),
QT_MOC_LITERAL(336, 3700, 10, 0),
QT_MOC_LITERAL(337, 3711, 21, 0),
QT_MOC_LITERAL(338, 3733, 10, 0),
QT_MOC_LITERAL(339, 3744, 8, 0),
QT_MOC_LITERAL(340, 3753, 12, 0),
QT_MOC_LITERAL(341, 3766, 10, 0),
QT_MOC_LITERAL(342, 3777, 9, 0),
QT_MOC_LITERAL(343, 3787, 11, 0),
QT_MOC_LITERAL(344, 3799, 14, 0),
QT_MOC_LITERAL(345, 3814, 8, 0),
QT_MOC_LITERAL(346, 3823, 7, 0),
QT_MOC_LITERAL(347, 3831, 11, 0),
QT_MOC_LITERAL(348, 3843, 15, 0),
QT_MOC_LITERAL(349, 3859, 13, 0),
QT_MOC_LITERAL(350, 3873, 12, 0),
QT_MOC_LITERAL(351, 3886, 15, 0),
QT_MOC_LITERAL(352, 3902, 12, 0),
QT_MOC_LITERAL(353, 3915, 15, 0),
QT_MOC_LITERAL(354, 3931, 12, 0),
QT_MOC_LITERAL(355, 3944, 16, 0),
QT_MOC_LITERAL(356, 3961, 13, 0),
QT_MOC_LITERAL(357, 3975, 15, 0),
QT_MOC_LITERAL(358, 3991, 12, 0),
QT_MOC_LITERAL(359, 4004, 7, 0),
QT_MOC_LITERAL(360, 4012, 4, 0),
QT_MOC_LITERAL(361, 4017, 16, 0),
QT_MOC_LITERAL(362, 4034, 13, 0),
QT_MOC_LITERAL(363, 4048, 20, 0),
QT_MOC_LITERAL(364, 4069, 17, 0),
QT_MOC_LITERAL(365, 4087, 25, 0),
QT_MOC_LITERAL(366, 4113, 22, 0),
QT_MOC_LITERAL(367, 4136, 12, 0),
QT_MOC_LITERAL(368, 4149, 9, 0),
QT_MOC_LITERAL(369, 4159, 12, 0),
QT_MOC_LITERAL(370, 4172, 9, 0),
QT_MOC_LITERAL(371, 4182, 21, 0),
QT_MOC_LITERAL(372, 4204, 18, 0),
QT_MOC_LITERAL(373, 4223, 11, 0),
QT_MOC_LITERAL(374, 4235, 8, 0),
QT_MOC_LITERAL(375, 4244, 14, 0),
QT_MOC_LITERAL(376, 4259, 9, 0),
QT_MOC_LITERAL(377, 4269, 17, 0),
QT_MOC_LITERAL(378, 4287, 12, 0),
QT_MOC_LITERAL(379, 4300, 9, 0),
QT_MOC_LITERAL(380, 4310, 14, 0),
QT_MOC_LITERAL(381, 4325, 11, 0),
QT_MOC_LITERAL(382, 4337, 16, 0),
QT_MOC_LITERAL(383, 4354, 13, 0),
QT_MOC_LITERAL(384, 4368, 14, 0),
QT_MOC_LITERAL(385, 4383, 11, 0),
QT_MOC_LITERAL(386, 4395, 11, 0),
QT_MOC_LITERAL(387, 4407, 8, 0),
QT_MOC_LITERAL(388, 4416, 11, 0),
QT_MOC_LITERAL(389, 4428, 8, 0),
QT_MOC_LITERAL(390, 4437, 8, 0),
QT_MOC_LITERAL(391, 4446, 5, 0),
QT_MOC_LITERAL(392, 4452, 14, 0),
QT_MOC_LITERAL(393, 4467, 14, 0),
QT_MOC_LITERAL(394, 4482, 11, 0),
QT_MOC_LITERAL(395, 4494, 15, 0),
QT_MOC_LITERAL(396, 4510, 12, 0),
QT_MOC_LITERAL(397, 4523, 15, 0),
QT_MOC_LITERAL(398, 4539, 12, 0),
QT_MOC_LITERAL(399, 4552, 13, 0),
QT_MOC_LITERAL(400, 4566, 10, 0),
QT_MOC_LITERAL(401, 4577, 11, 0),
QT_MOC_LITERAL(402, 4589, 6, 0),
QT_MOC_LITERAL(403, 4596, 14, 0),
QT_MOC_LITERAL(404, 4611, 11, 0),
QT_MOC_LITERAL(405, 4623, 19, 0),
QT_MOC_LITERAL(406, 4643, 16, 0),
QT_MOC_LITERAL(407, 4660, 21, 0),
QT_MOC_LITERAL(408, 4682, 2, 0),
QT_MOC_LITERAL(409, 4685, 2, 0),
QT_MOC_LITERAL(410, 4688, 19, 0),
QT_MOC_LITERAL(411, 4708, 17, 0),
QT_MOC_LITERAL(412, 4726, 18, 0),
QT_MOC_LITERAL(413, 4745, 6, 0),
QT_MOC_LITERAL(414, 4752, 19, 0),
QT_MOC_LITERAL(415, 4772, 17, 0)
    },
    "MMVARILib::_DMMVARI\0exception\0\0code\0source\0disc\0help\0propertyChanged\0name\0"
    "signal\0argc\0argv\0AboutBox\0AddNotchFreq\0wFreq\0AdjustClock\0wWidth\0AttachLongArray\0"
    "int&\0pDist\0pSrc\0wSize\0CalcCustomCharacteristic\0double&\0pAmp\0pPhase\0wMaxFreq\0"
    "CreateCustomFilter\0nTaps\0pCoeff\0CreateCustomFilterByIDFT\0pFreqSamp\0wDB\0"
    "CreateCustomFilterByKW\0nType\0dblFC1\0dblFC2\0CreateVaricodeList\0strName\0"
    "DeleteCustomFilter\0DeleteNotch\0nIndex\0FindNotchFreq\0GetSendText\0GetVariType\0"
    "PlayBack\0wSec\0ReadFFT\0pArray\0wCount\0SendCWID\0strText\0SendChar\0wChar\0SendText\0"
    "SendTone\0SetClockAdjust\0wTone\0dblSampleFreq\0SetTX\0wCmd\0bAFC\0bCodeBAUDOT\0"
    "bCodeMM\0bOverLevel\0bPTTLines\0nLine\0bRTTYFFT\0bRxEnabled\0bSQ\0bSync\0bUOS\0"
    "dblBandWidth\0dblFreqError\0dblRxShift\0dblSpeed\0setBAFC\0rhs\0setBATC\0bATC\0"
    "setBActive\0bActive\0setBAddStartCR\0bAddStartCR\0setBAddStopCR\0bAddStopCR\0"
    "setBCOMFSK\0bCOMFSK\0setBCOMFSKINV\0bCOMFSKINV\0setBCustomFilter\0bCustomFilter\0"
    "setBHPF\0bHPF\0setBLoopExternal\0bLoopExternal\0setBMetricSqMFSK\0bMetricSqMFSK\0"
    "setBNET\0bNET\0setBNotch\0bNotch\0setBPTTLines\0setBPTTLock\0bPTTLock\0setBPlayBack\0"
    "bPlayBack\0setBRTTYFFT\0setBReqRX\0bReqRX\0setBRxEnabled\0setBSendSingleTone\0"
    "bSendSingleTone\0setBTX\0bTX\0setBTreatCenterMFSK\0bTreatCenterMFSK\0setBUOS\0"
    "setDblCustomSampleFreq\0dblCustomSampleFreq\0setDblFFTSampleFreq\0dblFFTSampleFreq\0"
    "setDblRxShift\0setDblSampleFreq\0setDblSpeed\0setDblTxOffset\0dblTxOffset\0"
    "setDblTxShift\0dblTxShift\0setDwATC\0dwATC\0setDwHandle\0dwHandle\0setDwSampleBase\0"
    "dwSampleBase\0setHWnd\0hWnd\0setNBPF\0nBPF\0setStatComOpen\0statComOpen\0setStatIsPlaying\0"
    "statIsPlaying\0setStatLostRX\0statLostRX\0setStatLostTX\0statLostTX\0setStatSoundOpen\0"
    "statSoundOpen\0setStrMode\0setStrPTTPort\0strPTTPort\0setStrSoundID\0strSoundID\0"
    "setStrVersion\0strVersion\0setWAFCLevel\0wAFCLevel\0setWAFCWidth\0wAFCWidth\0"
    "setWBufferCount\0wBufferCount\0setWBufferMax\0wBufferMax\0setWCWSpeed\0wCWSpeed\0"
    "setWChannels\0wChannels\0setWCharset\0setWCollectType\0wCollectType\0setWDefaultCharset\0"
    "wDefaultCharset\0setWDiddleRTTY\0wDiddleRTTY\0setWFFTType\0wFFTType\0setWFFTWidth\0"
    "wFFTWidth\0setWLang\0wLang\0setWModGain\0wModGain\0setWMode\0setWModeMax\0wModeMax\0"
    "setWNotchFreq\0wNotchFreq\0setWNotchTaps\0wNotchTaps\0setWNotches\0setWNumNotches\0"
    "wNumNotches\0setWRxCarrier\0setWSQLevel\0setWSoundCH\0wSoundCH\0setWSoundRxFIFO\0"
    "wSoundRxFIFO\0setWSoundTxFIFO\0wSoundTxFIFO\0setWTxCarrier\0wTxCarrier\0setWTxState\0"
    "wTxState\0setWWaveMax\0wWaveMax\0strMode\0strModeList\0wCharset\0wMetricMFSK\0nPhase\0"
    "wMode\0wNotches\0wRxCarrier\0wRxCenter\0wSN\0wSQLevel\0control\0MMVX_COLLECTTYPE\0"
    "collectNONE\0collectSYNC\0collectWAVE\0MMVX_ERRORCODE\0errorNONE\0errorLostRX\0"
    "errorLostTX\0errorSoundOpen\0errorComOpen\0MMVX_PTTLINES\0pttlineRTS\0pttlineDTR\0"
    "pttlineTXD\0MMVX_TXCMD\0cmdtxRX\0cmdtxTX\0cmdtxREQRX\0cmdtxCW\0cmdtxTONE\0MMVX_TXSTATE\0"
    "txstateRX\0txstateTX\0txstateREQRX\0txstateWAIT\0txstateTONE\0MMVX_VIEWTYPE\0"
    "viewtypeFFT\0viewtypeWATER\0viewtypeWAVE\0viewtypeFREQERR\0viewtypeSMALLWATER\0"
    "MMVARILib::MMVARI\0Event Interface 1\0_DMMVARIEvents\0OnClockAdjust\0OnDrawFFT\0"
    "OnDrawWave\0pArray1\0pArray2\0OnError\0nErrorCode\0OnGetTxChar\0OnMode\0mIndex\0OnNET\0"
    "OnPTT\0wTX\0OnPlayBack\0wStat\0OnRxCarrier\0OnRxChar\0strChar\0OnSpeed\0OnTiming\0"
    "dwTiming\0wUnit\0OnTxCarrier\0OnTxState\0wState\0MMVARILib::_DXMMVBtn\0FontChanged\0"
    "stdole::Font*\0Font\0SetCaption\0Caption\0SetEnabled\0Enabled\0SetFaceColor\0FaceColor\0"
    "SetFont\0SetState\0State\0SetTextColor\0TextColor\0SetToggled\0Toggled\0SetVisible\0"
    "Visible\0MMVARILib::XMMVBtn\0_DXMMVBtnEvents\0OnLButtonClick\0OnRButtonClick\0"
    "MMVARILib::_DXMMVLvl\0BorderStyleChanged\0BorderStyle\0Clear\0Draw\0DrawCustom\0"
    "wSig\0wSq\0fOver\0SetBackColor\0BackColor\0SetBorderStyle\0SetLineColor\0LineColor\0"
    "SetMaxLevel\0MaxLevel\0SetOffColor\0OffColor\0SetOnColor\0OnColor\0SetOverColor\0"
    "OverColor\0SetTxColor\0TxColor\0SetUnlockColor\0UnlockColor\0MMVARILib::XMMVLvl\0"
    "_DXMMVLvlEvents\0OnLMouseDown\0level\0OnLMouseMove\0OnLMouseUp\0OnRMouseDown\0"
    "OnRMouseMove\0OnRMouseUp\0MMVARILib::_DXMMVView\0ClearWater\0ColorFFT\0ColorFreqErr\0"
    "ColorWater\0ColorWave\0DrawFreqErr\0DrawSmallWater\0DrawWave\0Refresh\0SetColorFFT\0"
    "SetColorFreqErr\0SetColorWater\0SetColorWave\0SetWaterPalette\0WaterPalette\0"
    "setBAttachMouse\0bAttachMouse\0setBFollowRxFreq\0bFollowRxFreq\0setBHighQuality\0"
    "bHighQuality\0setBLSB\0bLSB\0setBShowErrorMsg\0bShowErrorMsg\0setBShowNotchMarkers\0"
    "bShowNotchMarkers\0setBShowSubChannelMarkers\0bShowSubChannelMarkers\0setBShowSync\0"
    "bShowSync\0setBWaterAGC\0bWaterAGC\0setBWindowsMouseEvent\0bWindowsMouseEvent\0"
    "setDwFreqHz\0dwFreqHz\0setStrErrorMsg\0setStrMsg\0setStrSubChannels\0setWBaseFreq\0"
    "wBaseFreq\0setWCursorFreq\0wCursorFreq\0setWMouseChannel\0wMouseChannel\0"
    "setWMouseNotch\0wMouseNotch\0setWPixelXW\0wPixelXW\0setWPixelYW\0wPixelYW\0setWType\0"
    "wType\0setWWaterLevel\0setWWaterNoise\0wWaterNoise\0setWWaterNoiseH\0wWaterNoiseH\0"
    "setWWaterNoiseL\0wWaterNoiseL\0setWWidthFreq\0wWidthFreq\0strErrorMsg\0strMsg\0"
    "strSubChannels\0wWaterLevel\0MMVARILib::XMMVView\0_DXMMVViewEvents\0OnWindowsLMouseDblClk\0"
    "wX\0wY\0OnWindowsLMouseDown\0OnWindowsLMouseUp\0OnWindowsMouseMove\0dwFlag\0"
    "OnWindowsRMouseDown\0OnWindowsRMouseUp\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_MMVARILib___DMMVARI[] = {

 // content:
    7, // revision
    0,  // classname
    0, 0, // classinfo
    121, 14, // methods
    60, 1040, // properties
    6, 1220, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 619, 2, 5,
    7, 1, 628, 2, 5,
    9, 3, 631, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 0, 638, 2, 9,
    13, 1, 639, 2, 9,
    15, 1, 642, 2, 9,
    17, 3, 645, 2, 9,
    22, 4, 652, 2, 9,
    27, 2, 661, 2, 9,
    30, 3, 666, 2, 9,
    33, 5, 673, 2, 9,
    37, 1, 684, 2, 9,
    39, 0, 687, 2, 9,
    40, 1, 688, 2, 9,
    42, 1, 691, 2, 9,
    43, 0, 694, 2, 9,
    44, 1, 695, 2, 9,
    45, 1, 698, 2, 9,
    47, 2, 701, 2, 9,
    50, 1, 706, 2, 9,
    52, 1, 709, 2, 9,
    54, 1, 712, 2, 9,
    55, 0, 715, 2, 9,
    56, 2, 716, 2, 9,
    59, 1, 721, 2, 9,
    61, 1, 724, 2, 9,
    62, 1, 727, 2, 9,
    63, 1, 730, 2, 9,
    64, 1, 733, 2, 9,
    65, 1, 736, 2, 9,
    67, 1, 739, 2, 9,
    68, 1, 742, 2, 9,
    69, 1, 745, 2, 9,
    70, 1, 748, 2, 9,
    71, 1, 751, 2, 9,
    72, 1, 754, 2, 9,
    73, 1, 757, 2, 9,
    74, 1, 760, 2, 9,
    75, 1, 763, 2, 9,
    76, 2, 766, 2, 9,
    78, 1, 771, 2, 9,
    80, 1, 774, 2, 9,
    82, 1, 777, 2, 9,
    84, 1, 780, 2, 9,
    86, 1, 783, 2, 9,
    88, 1, 786, 2, 9,
    90, 1, 789, 2, 9,
    92, 1, 792, 2, 9,
    94, 1, 795, 2, 9,
    96, 1, 798, 2, 9,
    98, 1, 801, 2, 9,
    100, 1, 804, 2, 9,
    102, 2, 807, 2, 9,
    103, 1, 812, 2, 9,
    105, 1, 815, 2, 9,
    107, 2, 818, 2, 9,
    108, 1, 823, 2, 9,
    110, 2, 826, 2, 9,
    111, 1, 831, 2, 9,
    113, 1, 834, 2, 9,
    115, 1, 837, 2, 9,
    117, 2, 840, 2, 9,
    118, 1, 845, 2, 9,
    120, 1, 848, 2, 9,
    122, 2, 851, 2, 9,
    123, 1, 856, 2, 9,
    124, 2, 859, 2, 9,
    125, 1, 864, 2, 9,
    127, 1, 867, 2, 9,
    129, 1, 870, 2, 9,
    131, 1, 873, 2, 9,
    133, 1, 876, 2, 9,
    135, 1, 879, 2, 9,
    137, 1, 882, 2, 9,
    139, 1, 885, 2, 9,
    141, 1, 888, 2, 9,
    143, 1, 891, 2, 9,
    145, 1, 894, 2, 9,
    147, 1, 897, 2, 9,
    149, 2, 900, 2, 9,
    150, 1, 905, 2, 9,
    152, 1, 908, 2, 9,
    154, 1, 911, 2, 9,
    156, 1, 914, 2, 9,
    158, 1, 917, 2, 9,
    160, 1, 920, 2, 9,
    162, 1, 923, 2, 9,
    164, 1, 926, 2, 9,
    166, 1, 929, 2, 9,
    168, 2, 932, 2, 9,
    169, 1, 937, 2, 9,
    171, 1, 940, 2, 9,
    173, 1, 943, 2, 9,
    175, 1, 946, 2, 9,
    177, 1, 949, 2, 9,
    179, 1, 952, 2, 9,
    181, 1, 955, 2, 9,
    183, 2, 958, 2, 9,
    184, 1, 963, 2, 9,
    186, 1, 966, 2, 9,
    188, 1, 969, 2, 9,
    190, 2, 972, 2, 9,
    191, 1, 977, 2, 9,
    193, 2, 980, 2, 9,
    194, 2, 985, 2, 9,
    195, 1, 990, 2, 9,
    197, 1, 993, 2, 9,
    199, 1, 996, 2, 9,
    201, 1, 999, 2, 9,
    203, 1, 1002, 2, 9,
    205, 1, 1005, 2, 9,
    207, 1, 1008, 2, 9,
    208, 1, 1011, 2, 9,
    209, 1, 1014, 2, 9,
    210, 2, 1017, 2, 9,
    212, 1, 1022, 2, 9,
    213, 1, 1025, 2, 9,
    214, 1, 1028, 2, 9,
    215, 1, 1031, 2, 9,
    216, 1, 1034, 2, 9,
    217, 1, 1037, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 14,
    QMetaType::Void, QMetaType::Int, 16,
    QMetaType::Void, 0x80000000 | 18, 0x80000000 | 18, QMetaType::Int, 19, 20, 21,
    QMetaType::Bool, 0x80000000 | 23, 0x80000000 | 23, QMetaType::Int, QMetaType::Int, 24, 25, 16, 26,
    QMetaType::Bool, QMetaType::Int, 0x80000000 | 23, 28, 29,
    QMetaType::Bool, QMetaType::Int, 0x80000000 | 23, QMetaType::Int, 28, 31, 32,
    QMetaType::Bool, QMetaType::Int, QMetaType::Int, QMetaType::Double, QMetaType::Double, QMetaType::Int, 34, 28, 35, 36, 32,
    QMetaType::Bool, QMetaType::QString, 38,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 41,
    QMetaType::Int, QMetaType::Int, 14,
    QMetaType::QString,
    QMetaType::QString, QMetaType::Int, 41,
    QMetaType::Bool, QMetaType::Int, 46,
    QMetaType::Int, 0x80000000 | 18, QMetaType::Int, 48, 49,
    QMetaType::Int, QMetaType::QString, 51,
    QMetaType::Int, QMetaType::Int, 53,
    QMetaType::Int, QMetaType::QString, 51,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, QMetaType::Double, 57, 58,
    QMetaType::Void, QMetaType::Int, 60,
    QMetaType::Int, QMetaType::Int, 41,
    QMetaType::Int, QMetaType::Int, 41,
    QMetaType::Int, QMetaType::Int, 41,
    QMetaType::Int, QMetaType::Int, 41,
    QMetaType::Int, QMetaType::Int, 66,
    QMetaType::Int, QMetaType::Int, 41,
    QMetaType::Int, QMetaType::Int, 41,
    QMetaType::Int, QMetaType::Int, 41,
    QMetaType::Int, QMetaType::Int, 41,
    QMetaType::Int, QMetaType::Int, 41,
    QMetaType::Double, QMetaType::Int, 41,
    QMetaType::Double, QMetaType::Int, 41,
    QMetaType::Double, QMetaType::Int, 41,
    QMetaType::Double, QMetaType::Int, 41,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 41, 77,
    QMetaType::Void, QMetaType::Bool, 79,
    QMetaType::Void, QMetaType::Bool, 81,
    QMetaType::Void, QMetaType::Bool, 83,
    QMetaType::Void, QMetaType::Bool, 85,
    QMetaType::Void, QMetaType::Bool, 87,
    QMetaType::Void, QMetaType::Bool, 89,
    QMetaType::Void, QMetaType::Bool, 91,
    QMetaType::Void, QMetaType::Bool, 93,
    QMetaType::Void, QMetaType::Bool, 95,
    QMetaType::Void, QMetaType::Bool, 97,
    QMetaType::Void, QMetaType::Bool, 99,
    QMetaType::Void, QMetaType::Bool, 101,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 66, 77,
    QMetaType::Void, QMetaType::Bool, 104,
    QMetaType::Void, QMetaType::Bool, 106,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 41, 77,
    QMetaType::Void, QMetaType::Bool, 109,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 41, 77,
    QMetaType::Void, QMetaType::Bool, 112,
    QMetaType::Void, QMetaType::Bool, 114,
    QMetaType::Void, QMetaType::Bool, 116,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 41, 77,
    QMetaType::Void, QMetaType::Double, 119,
    QMetaType::Void, QMetaType::Double, 121,
    QMetaType::Void, QMetaType::Int, QMetaType::Double, 41, 77,
    QMetaType::Void, QMetaType::Double, 58,
    QMetaType::Void, QMetaType::Int, QMetaType::Double, 41, 77,
    QMetaType::Void, QMetaType::Double, 126,
    QMetaType::Void, QMetaType::Double, 128,
    QMetaType::Void, QMetaType::Int, 130,
    QMetaType::Void, QMetaType::Int, 132,
    QMetaType::Void, QMetaType::Int, 134,
    QMetaType::Void, QMetaType::Int, 136,
    QMetaType::Void, QMetaType::Int, 138,
    QMetaType::Void, QMetaType::Int, 140,
    QMetaType::Void, QMetaType::Int, 142,
    QMetaType::Void, QMetaType::Int, 144,
    QMetaType::Void, QMetaType::Int, 146,
    QMetaType::Void, QMetaType::Int, 148,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, 41, 77,
    QMetaType::Void, QMetaType::QString, 151,
    QMetaType::Void, QMetaType::QString, 153,
    QMetaType::Void, QMetaType::QString, 155,
    QMetaType::Void, QMetaType::Int, 157,
    QMetaType::Void, QMetaType::Int, 159,
    QMetaType::Void, QMetaType::Int, 161,
    QMetaType::Void, QMetaType::Int, 163,
    QMetaType::Void, QMetaType::Int, 165,
    QMetaType::Void, QMetaType::Int, 167,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 41, 77,
    QMetaType::Void, QMetaType::Int, 170,
    QMetaType::Void, QMetaType::Int, 172,
    QMetaType::Void, QMetaType::Int, 174,
    QMetaType::Void, QMetaType::Int, 176,
    QMetaType::Void, QMetaType::Int, 178,
    QMetaType::Void, QMetaType::Int, 180,
    QMetaType::Void, QMetaType::Int, 182,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 41, 77,
    QMetaType::Void, QMetaType::Int, 185,
    QMetaType::Void, QMetaType::Int, 187,
    QMetaType::Void, QMetaType::Int, 189,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 41, 77,
    QMetaType::Void, QMetaType::Int, 192,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 41, 77,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 41, 77,
    QMetaType::Void, QMetaType::Int, 196,
    QMetaType::Void, QMetaType::Int, 198,
    QMetaType::Void, QMetaType::Int, 200,
    QMetaType::Void, QMetaType::Int, 202,
    QMetaType::Void, QMetaType::Int, 204,
    QMetaType::Void, QMetaType::Int, 206,
    QMetaType::QString, QMetaType::Int, 41,
    QMetaType::QString, QMetaType::Int, 41,
    QMetaType::Int, QMetaType::Int, 41,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, 41, 211,
    QMetaType::Int, QMetaType::Int, 41,
    QMetaType::Int, QMetaType::Int, 41,
    QMetaType::Int, QMetaType::Int, 41,
    QMetaType::Int, QMetaType::Int, 41,
    QMetaType::Int, QMetaType::Int, 41,
    QMetaType::Int, QMetaType::Int, 41,

 // properties: name, type, flags
    79, QMetaType::Bool, 0x01015003, 		 // bool bATC
    81, QMetaType::Bool, 0x01015003, 		 // bool bActive
    83, QMetaType::Bool, 0x01015003, 		 // bool bAddStartCR
    85, QMetaType::Bool, 0x01015003, 		 // bool bAddStopCR
    87, QMetaType::Bool, 0x01015003, 		 // bool bCOMFSK
    89, QMetaType::Bool, 0x01015003, 		 // bool bCOMFSKINV
    91, QMetaType::Bool, 0x01015003, 		 // bool bCustomFilter
    93, QMetaType::Bool, 0x01015003, 		 // bool bHPF
    95, QMetaType::Bool, 0x01015003, 		 // bool bLoopExternal
    97, QMetaType::Bool, 0x01015003, 		 // bool bMetricSqMFSK
    99, QMetaType::Bool, 0x01015003, 		 // bool bNET
    101, QMetaType::Bool, 0x01015003, 		 // bool bNotch
    104, QMetaType::Bool, 0x01015003, 		 // bool bPTTLock
    106, QMetaType::Bool, 0x01015003, 		 // bool bPlayBack
    109, QMetaType::Bool, 0x01015003, 		 // bool bReqRX
    112, QMetaType::Bool, 0x01015003, 		 // bool bSendSingleTone
    114, QMetaType::Bool, 0x01015003, 		 // bool bTX
    116, QMetaType::Bool, 0x01015003, 		 // bool bTreatCenterMFSK
    218, QMetaType::QString, 0x0a055003, 		 // QString control
    119, QMetaType::Double, 0x06015003, 		 // double dblCustomSampleFreq
    121, QMetaType::Double, 0x06015003, 		 // double dblFFTSampleFreq
    58, QMetaType::Double, 0x06015003, 		 // double dblSampleFreq
    126, QMetaType::Double, 0x06015003, 		 // double dblTxOffset
    128, QMetaType::Double, 0x06015003, 		 // double dblTxShift
    130, QMetaType::Int, 0x02015003, 		 // int dwATC
    132, QMetaType::Int, 0x02015003, 		 // int dwHandle
    134, QMetaType::Int, 0x02015003, 		 // int dwSampleBase
    136, QMetaType::Int, 0x02015003, 		 // int hWnd
    138, QMetaType::Int, 0x02015003, 		 // int nBPF
    140, QMetaType::Int, 0x02015003, 		 // int statComOpen
    142, QMetaType::Int, 0x02015003, 		 // int statIsPlaying
    144, QMetaType::Int, 0x02015003, 		 // int statLostRX
    146, QMetaType::Int, 0x02015003, 		 // int statLostTX
    148, QMetaType::Int, 0x02015003, 		 // int statSoundOpen
    151, QMetaType::QString, 0x0a015003, 		 // QString strPTTPort
    153, QMetaType::QString, 0x0a015003, 		 // QString strSoundID
    155, QMetaType::QString, 0x0a015003, 		 // QString strVersion
    157, QMetaType::Int, 0x02015003, 		 // int wAFCLevel
    159, QMetaType::Int, 0x02015003, 		 // int wAFCWidth
    161, QMetaType::Int, 0x02015003, 		 // int wBufferCount
    163, QMetaType::Int, 0x02015003, 		 // int wBufferMax
    165, QMetaType::Int, 0x02015003, 		 // int wCWSpeed
    167, QMetaType::Int, 0x02015003, 		 // int wChannels
    170, QMetaType::Int, 0x02015003, 		 // int wCollectType
    172, QMetaType::Int, 0x02015003, 		 // int wDefaultCharset
    174, QMetaType::Int, 0x02015003, 		 // int wDiddleRTTY
    176, QMetaType::Int, 0x02015003, 		 // int wFFTType
    178, QMetaType::Int, 0x02015003, 		 // int wFFTWidth
    180, QMetaType::Int, 0x02015003, 		 // int wLang
    182, QMetaType::Int, 0x02015003, 		 // int wModGain
    185, QMetaType::Int, 0x02015003, 		 // int wModeMax
    187, QMetaType::Int, 0x02015003, 		 // int wNotchFreq
    189, QMetaType::Int, 0x02015003, 		 // int wNotchTaps
    192, QMetaType::Int, 0x02015003, 		 // int wNumNotches
    196, QMetaType::Int, 0x02015003, 		 // int wSoundCH
    198, QMetaType::Int, 0x02015003, 		 // int wSoundRxFIFO
    200, QMetaType::Int, 0x02015003, 		 // int wSoundTxFIFO
    202, QMetaType::Int, 0x02015003, 		 // int wTxCarrier
    204, QMetaType::Int, 0x02015003, 		 // int wTxState
    206, QMetaType::Int, 0x02015003, 		 // int wWaveMax

 // enums: name, flags, count, data
    219, 0x0, 3, 1244, 
    223, 0x0, 5, 1250, 
    229, 0x0, 3, 1260, 
    233, 0x0, 5, 1266, 
    239, 0x0, 5, 1276, 
    245, 0x0, 5, 1286, 

 // enum data: key, value
    220, uint(MMVARILib::collectNONE),
    221, uint(MMVARILib::collectSYNC),
    222, uint(MMVARILib::collectWAVE),
    224, uint(MMVARILib::errorNONE),
    225, uint(MMVARILib::errorLostRX),
    226, uint(MMVARILib::errorLostTX),
    227, uint(MMVARILib::errorSoundOpen),
    228, uint(MMVARILib::errorComOpen),
    230, uint(MMVARILib::pttlineRTS),
    231, uint(MMVARILib::pttlineDTR),
    232, uint(MMVARILib::pttlineTXD),
    234, uint(MMVARILib::cmdtxRX),
    235, uint(MMVARILib::cmdtxTX),
    236, uint(MMVARILib::cmdtxREQRX),
    237, uint(MMVARILib::cmdtxCW),
    238, uint(MMVARILib::cmdtxTONE),
    240, uint(MMVARILib::txstateRX),
    241, uint(MMVARILib::txstateTX),
    242, uint(MMVARILib::txstateREQRX),
    243, uint(MMVARILib::txstateWAIT),
    244, uint(MMVARILib::txstateTONE),
    246, uint(MMVARILib::viewtypeFFT),
    247, uint(MMVARILib::viewtypeWATER),
    248, uint(MMVARILib::viewtypeWAVE),
    249, uint(MMVARILib::viewtypeFREQERR),
    250, uint(MMVARILib::viewtypeSMALLWATER),
    0 // eod
};

_DMMVARI::_DMMVARI(IDispatch *subobject, QAxObject *parent) :
    QAxObject(subobject, parent)
{
    internalRelease();
}

const QMetaObject _DMMVARI::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_MMVARILib___DMMVARI, nullptr, nullptr, nullptr }
};

void *_DMMVARI::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "MMVARILib::_DMMVARI"))
        return static_cast<void*>(const_cast<_DMMVARI*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_MMVARILib__MMVARI[] = {

 // content:
    7, // revision
    251,  // classname
    1, 14, // classinfo
    136, 16, // methods
    59, 1184, // properties
    6, 1361, // enums/sets
    0, 0, // constructors
    0, // flags
    18, // signal count

 // classinfo: key, value
    252, 253, 

// signal: name, argc, parameters, tag, flags
    254, 1, 696, 2, 5,
    255, 2, 699, 2, 5,
    256, 3, 704, 2, 5,
    259, 1, 711, 2, 5,
    261, 1, 714, 2, 5,
    262, 3, 717, 2, 5,
    264, 1, 724, 2, 5,
    265, 1, 727, 2, 5,
    267, 1, 730, 2, 5,
    269, 2, 733, 2, 5,
    270, 3, 738, 2, 5,
    272, 2, 745, 2, 5,
    273, 3, 750, 2, 5,
    276, 1, 757, 2, 5,
    277, 1, 760, 2, 5,
    1, 4, 763, 2, 5,
    7, 1, 772, 2, 5,
    9, 3, 775, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 0, 782, 2, 9,
    13, 1, 783, 2, 9,
    15, 1, 786, 2, 9,
    17, 3, 789, 2, 9,
    22, 4, 796, 2, 9,
    27, 2, 805, 2, 9,
    30, 3, 810, 2, 9,
    33, 5, 817, 2, 9,
    37, 1, 828, 2, 9,
    39, 0, 831, 2, 9,
    40, 1, 832, 2, 9,
    42, 1, 835, 2, 9,
    43, 0, 838, 2, 9,
    44, 1, 839, 2, 9,
    45, 1, 842, 2, 9,
    47, 2, 845, 2, 9,
    50, 1, 850, 2, 9,
    52, 1, 853, 2, 9,
    54, 1, 856, 2, 9,
    55, 0, 859, 2, 9,
    56, 2, 860, 2, 9,
    59, 1, 865, 2, 9,
    61, 1, 868, 2, 9,
    62, 1, 871, 2, 9,
    63, 1, 874, 2, 9,
    64, 1, 877, 2, 9,
    65, 1, 880, 2, 9,
    67, 1, 883, 2, 9,
    68, 1, 886, 2, 9,
    69, 1, 889, 2, 9,
    70, 1, 892, 2, 9,
    71, 1, 895, 2, 9,
    72, 1, 898, 2, 9,
    73, 1, 901, 2, 9,
    74, 1, 904, 2, 9,
    75, 1, 907, 2, 9,
    76, 2, 910, 2, 9,
    78, 1, 915, 2, 9,
    80, 1, 918, 2, 9,
    82, 1, 921, 2, 9,
    84, 1, 924, 2, 9,
    86, 1, 927, 2, 9,
    88, 1, 930, 2, 9,
    90, 1, 933, 2, 9,
    92, 1, 936, 2, 9,
    94, 1, 939, 2, 9,
    96, 1, 942, 2, 9,
    98, 1, 945, 2, 9,
    100, 1, 948, 2, 9,
    102, 2, 951, 2, 9,
    103, 1, 956, 2, 9,
    105, 1, 959, 2, 9,
    107, 2, 962, 2, 9,
    108, 1, 967, 2, 9,
    110, 2, 970, 2, 9,
    111, 1, 975, 2, 9,
    113, 1, 978, 2, 9,
    115, 1, 981, 2, 9,
    117, 2, 984, 2, 9,
    118, 1, 989, 2, 9,
    120, 1, 992, 2, 9,
    122, 2, 995, 2, 9,
    123, 1, 1000, 2, 9,
    124, 2, 1003, 2, 9,
    125, 1, 1008, 2, 9,
    127, 1, 1011, 2, 9,
    129, 1, 1014, 2, 9,
    131, 1, 1017, 2, 9,
    133, 1, 1020, 2, 9,
    135, 1, 1023, 2, 9,
    137, 1, 1026, 2, 9,
    139, 1, 1029, 2, 9,
    141, 1, 1032, 2, 9,
    143, 1, 1035, 2, 9,
    145, 1, 1038, 2, 9,
    147, 1, 1041, 2, 9,
    149, 2, 1044, 2, 9,
    150, 1, 1049, 2, 9,
    152, 1, 1052, 2, 9,
    154, 1, 1055, 2, 9,
    156, 1, 1058, 2, 9,
    158, 1, 1061, 2, 9,
    160, 1, 1064, 2, 9,
    162, 1, 1067, 2, 9,
    164, 1, 1070, 2, 9,
    166, 1, 1073, 2, 9,
    168, 2, 1076, 2, 9,
    169, 1, 1081, 2, 9,
    171, 1, 1084, 2, 9,
    173, 1, 1087, 2, 9,
    175, 1, 1090, 2, 9,
    177, 1, 1093, 2, 9,
    179, 1, 1096, 2, 9,
    181, 1, 1099, 2, 9,
    183, 2, 1102, 2, 9,
    184, 1, 1107, 2, 9,
    186, 1, 1110, 2, 9,
    188, 1, 1113, 2, 9,
    190, 2, 1116, 2, 9,
    191, 1, 1121, 2, 9,
    193, 2, 1124, 2, 9,
    194, 2, 1129, 2, 9,
    195, 1, 1134, 2, 9,
    197, 1, 1137, 2, 9,
    199, 1, 1140, 2, 9,
    201, 1, 1143, 2, 9,
    203, 1, 1146, 2, 9,
    205, 1, 1149, 2, 9,
    207, 1, 1152, 2, 9,
    208, 1, 1155, 2, 9,
    209, 1, 1158, 2, 9,
    210, 2, 1161, 2, 9,
    212, 1, 1166, 2, 9,
    213, 1, 1169, 2, 9,
    214, 1, 1172, 2, 9,
    215, 1, 1175, 2, 9,
    216, 1, 1178, 2, 9,
    217, 1, 1181, 2, 9,

// signal: parameters
    QMetaType::Void, 0x80000000 | 18, 48,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 18, 49, 48,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 18, 0x80000000 | 18, 49, 257, 258,
    QMetaType::Void, QMetaType::Int, 260,
    QMetaType::Void, 0x80000000 | 18, 53,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::QString, 41, 263, 207,
    QMetaType::Void, QMetaType::Int, 99,
    QMetaType::Void, QMetaType::Int, 266,
    QMetaType::Void, QMetaType::Int, 268,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 41, 14,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::Int, 41, 271, 53,
    QMetaType::Void, QMetaType::Int, QMetaType::Double, 41, 75,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, 41, 274, 275,
    QMetaType::Void, QMetaType::Int, 14,
    QMetaType::Void, QMetaType::Int, 278,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 14,
    QMetaType::Void, QMetaType::Int, 16,
    QMetaType::Void, 0x80000000 | 18, 0x80000000 | 18, QMetaType::Int, 19, 20, 21,
    QMetaType::Bool, 0x80000000 | 23, 0x80000000 | 23, QMetaType::Int, QMetaType::Int, 24, 25, 16, 26,
    QMetaType::Bool, QMetaType::Int, 0x80000000 | 23, 28, 29,
    QMetaType::Bool, QMetaType::Int, 0x80000000 | 23, QMetaType::Int, 28, 31, 32,
    QMetaType::Bool, QMetaType::Int, QMetaType::Int, QMetaType::Double, QMetaType::Double, QMetaType::Int, 34, 28, 35, 36, 32,
    QMetaType::Bool, QMetaType::QString, 38,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 41,
    QMetaType::Int, QMetaType::Int, 14,
    QMetaType::QString,
    QMetaType::QString, QMetaType::Int, 41,
    QMetaType::Bool, QMetaType::Int, 46,
    QMetaType::Int, 0x80000000 | 18, QMetaType::Int, 48, 49,
    QMetaType::Int, QMetaType::QString, 51,
    QMetaType::Int, QMetaType::Int, 53,
    QMetaType::Int, QMetaType::QString, 51,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, QMetaType::Double, 57, 58,
    QMetaType::Void, QMetaType::Int, 60,
    QMetaType::Int, QMetaType::Int, 41,
    QMetaType::Int, QMetaType::Int, 41,
    QMetaType::Int, QMetaType::Int, 41,
    QMetaType::Int, QMetaType::Int, 41,
    QMetaType::Int, QMetaType::Int, 66,
    QMetaType::Int, QMetaType::Int, 41,
    QMetaType::Int, QMetaType::Int, 41,
    QMetaType::Int, QMetaType::Int, 41,
    QMetaType::Int, QMetaType::Int, 41,
    QMetaType::Int, QMetaType::Int, 41,
    QMetaType::Double, QMetaType::Int, 41,
    QMetaType::Double, QMetaType::Int, 41,
    QMetaType::Double, QMetaType::Int, 41,
    QMetaType::Double, QMetaType::Int, 41,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 41, 77,
    QMetaType::Void, QMetaType::Bool, 79,
    QMetaType::Void, QMetaType::Bool, 81,
    QMetaType::Void, QMetaType::Bool, 83,
    QMetaType::Void, QMetaType::Bool, 85,
    QMetaType::Void, QMetaType::Bool, 87,
    QMetaType::Void, QMetaType::Bool, 89,
    QMetaType::Void, QMetaType::Bool, 91,
    QMetaType::Void, QMetaType::Bool, 93,
    QMetaType::Void, QMetaType::Bool, 95,
    QMetaType::Void, QMetaType::Bool, 97,
    QMetaType::Void, QMetaType::Bool, 99,
    QMetaType::Void, QMetaType::Bool, 101,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 66, 77,
    QMetaType::Void, QMetaType::Bool, 104,
    QMetaType::Void, QMetaType::Bool, 106,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 41, 77,
    QMetaType::Void, QMetaType::Bool, 109,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 41, 77,
    QMetaType::Void, QMetaType::Bool, 112,
    QMetaType::Void, QMetaType::Bool, 114,
    QMetaType::Void, QMetaType::Bool, 116,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 41, 77,
    QMetaType::Void, QMetaType::Double, 119,
    QMetaType::Void, QMetaType::Double, 121,
    QMetaType::Void, QMetaType::Int, QMetaType::Double, 41, 77,
    QMetaType::Void, QMetaType::Double, 58,
    QMetaType::Void, QMetaType::Int, QMetaType::Double, 41, 77,
    QMetaType::Void, QMetaType::Double, 126,
    QMetaType::Void, QMetaType::Double, 128,
    QMetaType::Void, QMetaType::Int, 130,
    QMetaType::Void, QMetaType::Int, 132,
    QMetaType::Void, QMetaType::Int, 134,
    QMetaType::Void, QMetaType::Int, 136,
    QMetaType::Void, QMetaType::Int, 138,
    QMetaType::Void, QMetaType::Int, 140,
    QMetaType::Void, QMetaType::Int, 142,
    QMetaType::Void, QMetaType::Int, 144,
    QMetaType::Void, QMetaType::Int, 146,
    QMetaType::Void, QMetaType::Int, 148,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, 41, 77,
    QMetaType::Void, QMetaType::QString, 151,
    QMetaType::Void, QMetaType::QString, 153,
    QMetaType::Void, QMetaType::QString, 155,
    QMetaType::Void, QMetaType::Int, 157,
    QMetaType::Void, QMetaType::Int, 159,
    QMetaType::Void, QMetaType::Int, 161,
    QMetaType::Void, QMetaType::Int, 163,
    QMetaType::Void, QMetaType::Int, 165,
    QMetaType::Void, QMetaType::Int, 167,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 41, 77,
    QMetaType::Void, QMetaType::Int, 170,
    QMetaType::Void, QMetaType::Int, 172,
    QMetaType::Void, QMetaType::Int, 174,
    QMetaType::Void, QMetaType::Int, 176,
    QMetaType::Void, QMetaType::Int, 178,
    QMetaType::Void, QMetaType::Int, 180,
    QMetaType::Void, QMetaType::Int, 182,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 41, 77,
    QMetaType::Void, QMetaType::Int, 185,
    QMetaType::Void, QMetaType::Int, 187,
    QMetaType::Void, QMetaType::Int, 189,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 41, 77,
    QMetaType::Void, QMetaType::Int, 192,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 41, 77,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 41, 77,
    QMetaType::Void, QMetaType::Int, 196,
    QMetaType::Void, QMetaType::Int, 198,
    QMetaType::Void, QMetaType::Int, 200,
    QMetaType::Void, QMetaType::Int, 202,
    QMetaType::Void, QMetaType::Int, 204,
    QMetaType::Void, QMetaType::Int, 206,
    QMetaType::QString, QMetaType::Int, 41,
    QMetaType::QString, QMetaType::Int, 41,
    QMetaType::Int, QMetaType::Int, 41,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, 41, 211,
    QMetaType::Int, QMetaType::Int, 41,
    QMetaType::Int, QMetaType::Int, 41,
    QMetaType::Int, QMetaType::Int, 41,
    QMetaType::Int, QMetaType::Int, 41,
    QMetaType::Int, QMetaType::Int, 41,
    QMetaType::Int, QMetaType::Int, 41,

 // properties: name, type, flags
    79, QMetaType::Bool, 0x01015003, 		 // bool bATC
    81, QMetaType::Bool, 0x01015003, 		 // bool bActive
    83, QMetaType::Bool, 0x01015003, 		 // bool bAddStartCR
    85, QMetaType::Bool, 0x01015003, 		 // bool bAddStopCR
    87, QMetaType::Bool, 0x01015003, 		 // bool bCOMFSK
    89, QMetaType::Bool, 0x01015003, 		 // bool bCOMFSKINV
    91, QMetaType::Bool, 0x01015003, 		 // bool bCustomFilter
    93, QMetaType::Bool, 0x01015003, 		 // bool bHPF
    95, QMetaType::Bool, 0x01015003, 		 // bool bLoopExternal
    97, QMetaType::Bool, 0x01015003, 		 // bool bMetricSqMFSK
    99, QMetaType::Bool, 0x01015003, 		 // bool bNET
    101, QMetaType::Bool, 0x01015003, 		 // bool bNotch
    104, QMetaType::Bool, 0x01015003, 		 // bool bPTTLock
    106, QMetaType::Bool, 0x01015003, 		 // bool bPlayBack
    109, QMetaType::Bool, 0x01015003, 		 // bool bReqRX
    112, QMetaType::Bool, 0x01015003, 		 // bool bSendSingleTone
    114, QMetaType::Bool, 0x01015003, 		 // bool bTX
    116, QMetaType::Bool, 0x01015003, 		 // bool bTreatCenterMFSK
    119, QMetaType::Double, 0x06015003, 		 // double dblCustomSampleFreq
    121, QMetaType::Double, 0x06015003, 		 // double dblFFTSampleFreq
    58, QMetaType::Double, 0x06015003, 		 // double dblSampleFreq
    126, QMetaType::Double, 0x06015003, 		 // double dblTxOffset
    128, QMetaType::Double, 0x06015003, 		 // double dblTxShift
    130, QMetaType::Int, 0x02015003, 		 // int dwATC
    132, QMetaType::Int, 0x02015003, 		 // int dwHandle
    134, QMetaType::Int, 0x02015003, 		 // int dwSampleBase
    136, QMetaType::Int, 0x02015003, 		 // int hWnd
    138, QMetaType::Int, 0x02015003, 		 // int nBPF
    140, QMetaType::Int, 0x02015003, 		 // int statComOpen
    142, QMetaType::Int, 0x02015003, 		 // int statIsPlaying
    144, QMetaType::Int, 0x02015003, 		 // int statLostRX
    146, QMetaType::Int, 0x02015003, 		 // int statLostTX
    148, QMetaType::Int, 0x02015003, 		 // int statSoundOpen
    151, QMetaType::QString, 0x0a015003, 		 // QString strPTTPort
    153, QMetaType::QString, 0x0a015003, 		 // QString strSoundID
    155, QMetaType::QString, 0x0a015003, 		 // QString strVersion
    157, QMetaType::Int, 0x02015003, 		 // int wAFCLevel
    159, QMetaType::Int, 0x02015003, 		 // int wAFCWidth
    161, QMetaType::Int, 0x02015003, 		 // int wBufferCount
    163, QMetaType::Int, 0x02015003, 		 // int wBufferMax
    165, QMetaType::Int, 0x02015003, 		 // int wCWSpeed
    167, QMetaType::Int, 0x02015003, 		 // int wChannels
    170, QMetaType::Int, 0x02015003, 		 // int wCollectType
    172, QMetaType::Int, 0x02015003, 		 // int wDefaultCharset
    174, QMetaType::Int, 0x02015003, 		 // int wDiddleRTTY
    176, QMetaType::Int, 0x02015003, 		 // int wFFTType
    178, QMetaType::Int, 0x02015003, 		 // int wFFTWidth
    180, QMetaType::Int, 0x02015003, 		 // int wLang
    182, QMetaType::Int, 0x02015003, 		 // int wModGain
    185, QMetaType::Int, 0x02015003, 		 // int wModeMax
    187, QMetaType::Int, 0x02015003, 		 // int wNotchFreq
    189, QMetaType::Int, 0x02015003, 		 // int wNotchTaps
    192, QMetaType::Int, 0x02015003, 		 // int wNumNotches
    196, QMetaType::Int, 0x02015003, 		 // int wSoundCH
    198, QMetaType::Int, 0x02015003, 		 // int wSoundRxFIFO
    200, QMetaType::Int, 0x02015003, 		 // int wSoundTxFIFO
    202, QMetaType::Int, 0x02015003, 		 // int wTxCarrier
    204, QMetaType::Int, 0x02015003, 		 // int wTxState
    206, QMetaType::Int, 0x02015003, 		 // int wWaveMax

 // enums: name, flags, count, data
    219, 0x0, 3, 1385, 
    223, 0x0, 5, 1391, 
    229, 0x0, 3, 1401, 
    233, 0x0, 5, 1407, 
    239, 0x0, 5, 1417, 
    245, 0x0, 5, 1427, 

 // enum data: key, value
    220, uint(MMVARILib::collectNONE),
    221, uint(MMVARILib::collectSYNC),
    222, uint(MMVARILib::collectWAVE),
    224, uint(MMVARILib::errorNONE),
    225, uint(MMVARILib::errorLostRX),
    226, uint(MMVARILib::errorLostTX),
    227, uint(MMVARILib::errorSoundOpen),
    228, uint(MMVARILib::errorComOpen),
    230, uint(MMVARILib::pttlineRTS),
    231, uint(MMVARILib::pttlineDTR),
    232, uint(MMVARILib::pttlineTXD),
    234, uint(MMVARILib::cmdtxRX),
    235, uint(MMVARILib::cmdtxTX),
    236, uint(MMVARILib::cmdtxREQRX),
    237, uint(MMVARILib::cmdtxCW),
    238, uint(MMVARILib::cmdtxTONE),
    240, uint(MMVARILib::txstateRX),
    241, uint(MMVARILib::txstateTX),
    242, uint(MMVARILib::txstateREQRX),
    243, uint(MMVARILib::txstateWAIT),
    244, uint(MMVARILib::txstateTONE),
    246, uint(MMVARILib::viewtypeFFT),
    247, uint(MMVARILib::viewtypeWATER),
    248, uint(MMVARILib::viewtypeWAVE),
    249, uint(MMVARILib::viewtypeFREQERR),
    250, uint(MMVARILib::viewtypeSMALLWATER),
    0 // eod
};

MMVARI::MMVARI(QWidget *parent, Qt::WindowFlags f) :
    QAxWidget(parent, f)
{
    setControl(QStringLiteral("{9c0d49dd-5c05-456d-916b-98c4cf63172f}"));
}

const QMetaObject MMVARI::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_MMVARILib__MMVARI, nullptr, nullptr, nullptr }
};

void *MMVARI::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "MMVARILib::MMVARI"))
        return static_cast<void*>(const_cast<MMVARI*>(this));
    return QAxWidget::qt_metacast(_clname);
}
static const uint qt_meta_data_MMVARILib___DXMMVBtn[] = {

 // content:
    7, // revision
    279,  // classname
    0, 0, // classinfo
    13, 14, // methods
    10, 128, // properties
    6, 158, // enums/sets
    0, 0, // constructors
    0, // flags
    4, // signal count

// signal: name, argc, parameters, tag, flags
    280, 1, 79, 2, 5,
    1, 4, 82, 2, 5,
    7, 1, 91, 2, 5,
    9, 3, 94, 2, 5,

// slot: name, argc, parameters, tag, flags
    283, 1, 101, 2, 9,
    285, 1, 104, 2, 9,
    287, 1, 107, 2, 9,
    289, 1, 110, 2, 9,
    290, 1, 113, 2, 9,
    292, 1, 116, 2, 9,
    294, 1, 119, 2, 9,
    296, 1, 122, 2, 9,
    135, 1, 125, 2, 9,

// signal: parameters
    QMetaType::Void, 0x80000000 | 281, 282,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void, QMetaType::QString, 284,
    QMetaType::Void, QMetaType::Bool, 286,
    QMetaType::Void, QMetaType::QColor, 288,
    QMetaType::Void, 0x80000000 | 281, 282,
    QMetaType::Void, QMetaType::Bool, 291,
    QMetaType::Void, QMetaType::QColor, 293,
    QMetaType::Void, QMetaType::Bool, 295,
    QMetaType::Void, QMetaType::Bool, 297,
    QMetaType::Void, QMetaType::Int, 136,

 // properties: name, type, flags
    284, QMetaType::QString, 0x0a015003, 		 // QString Caption
    286, QMetaType::Bool, 0x01015003, 		 // bool Enabled
    288, QMetaType::QColor, 0x43015003, 		 // QColor FaceColor
    282, 0x80000000 | 281, 0x00015003, 		 // stdole::Font* Font
    291, QMetaType::Bool, 0x01015003, 		 // bool State
    293, QMetaType::QColor, 0x43015003, 		 // QColor TextColor
    295, QMetaType::Bool, 0x01015003, 		 // bool Toggled
    297, QMetaType::Bool, 0x01015003, 		 // bool Visible
    218, QMetaType::QString, 0x0a055003, 		 // QString control
    136, QMetaType::Int, 0x02015003, 		 // int hWnd

 // enums: name, flags, count, data
    219, 0x0, 3, 182, 
    223, 0x0, 5, 188, 
    229, 0x0, 3, 198, 
    233, 0x0, 5, 204, 
    239, 0x0, 5, 214, 
    245, 0x0, 5, 224, 

 // enum data: key, value
    220, uint(MMVARILib::collectNONE),
    221, uint(MMVARILib::collectSYNC),
    222, uint(MMVARILib::collectWAVE),
    224, uint(MMVARILib::errorNONE),
    225, uint(MMVARILib::errorLostRX),
    226, uint(MMVARILib::errorLostTX),
    227, uint(MMVARILib::errorSoundOpen),
    228, uint(MMVARILib::errorComOpen),
    230, uint(MMVARILib::pttlineRTS),
    231, uint(MMVARILib::pttlineDTR),
    232, uint(MMVARILib::pttlineTXD),
    234, uint(MMVARILib::cmdtxRX),
    235, uint(MMVARILib::cmdtxTX),
    236, uint(MMVARILib::cmdtxREQRX),
    237, uint(MMVARILib::cmdtxCW),
    238, uint(MMVARILib::cmdtxTONE),
    240, uint(MMVARILib::txstateRX),
    241, uint(MMVARILib::txstateTX),
    242, uint(MMVARILib::txstateREQRX),
    243, uint(MMVARILib::txstateWAIT),
    244, uint(MMVARILib::txstateTONE),
    246, uint(MMVARILib::viewtypeFFT),
    247, uint(MMVARILib::viewtypeWATER),
    248, uint(MMVARILib::viewtypeWAVE),
    249, uint(MMVARILib::viewtypeFREQERR),
    250, uint(MMVARILib::viewtypeSMALLWATER),
    0 // eod
};

_DXMMVBtn::_DXMMVBtn(IDispatch *subobject, QAxObject *parent) :
    QAxObject(subobject, parent)
{
    internalRelease();
}

const QMetaObject _DXMMVBtn::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_MMVARILib___DXMMVBtn, nullptr, nullptr, nullptr }
};

void *_DXMMVBtn::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "MMVARILib::_DXMMVBtn"))
        return static_cast<void*>(const_cast<_DXMMVBtn*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_MMVARILib__XMMVBtn[] = {

 // content:
    7, // revision
    298,  // classname
    1, 14, // classinfo
    15, 16, // methods
    9, 142, // properties
    6, 169, // enums/sets
    0, 0, // constructors
    0, // flags
    6, // signal count

 // classinfo: key, value
    252, 299, 

// signal: name, argc, parameters, tag, flags
    280, 1, 91, 2, 5,
    300, 0, 94, 2, 5,
    301, 0, 95, 2, 5,
    1, 4, 96, 2, 5,
    7, 1, 105, 2, 5,
    9, 3, 108, 2, 5,

// slot: name, argc, parameters, tag, flags
    283, 1, 115, 2, 9,
    285, 1, 118, 2, 9,
    287, 1, 121, 2, 9,
    289, 1, 124, 2, 9,
    290, 1, 127, 2, 9,
    292, 1, 130, 2, 9,
    294, 1, 133, 2, 9,
    296, 1, 136, 2, 9,
    135, 1, 139, 2, 9,

// signal: parameters
    QMetaType::Void, 0x80000000 | 281, 282,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void, QMetaType::QString, 284,
    QMetaType::Void, QMetaType::Bool, 286,
    QMetaType::Void, QMetaType::QColor, 288,
    QMetaType::Void, 0x80000000 | 281, 282,
    QMetaType::Void, QMetaType::Bool, 291,
    QMetaType::Void, QMetaType::QColor, 293,
    QMetaType::Void, QMetaType::Bool, 295,
    QMetaType::Void, QMetaType::Bool, 297,
    QMetaType::Void, QMetaType::Int, 136,

 // properties: name, type, flags
    284, QMetaType::QString, 0x0a015003, 		 // QString Caption
    286, QMetaType::Bool, 0x01015003, 		 // bool Enabled
    288, QMetaType::QColor, 0x43015003, 		 // QColor FaceColor
    282, 0x80000000 | 281, 0x00015003, 		 // stdole::Font* Font
    291, QMetaType::Bool, 0x01015003, 		 // bool State
    293, QMetaType::QColor, 0x43015003, 		 // QColor TextColor
    295, QMetaType::Bool, 0x01015003, 		 // bool Toggled
    297, QMetaType::Bool, 0x01015003, 		 // bool Visible
    136, QMetaType::Int, 0x02015003, 		 // int hWnd

 // enums: name, flags, count, data
    219, 0x0, 3, 193, 
    223, 0x0, 5, 199, 
    229, 0x0, 3, 209, 
    233, 0x0, 5, 215, 
    239, 0x0, 5, 225, 
    245, 0x0, 5, 235, 

 // enum data: key, value
    220, uint(MMVARILib::collectNONE),
    221, uint(MMVARILib::collectSYNC),
    222, uint(MMVARILib::collectWAVE),
    224, uint(MMVARILib::errorNONE),
    225, uint(MMVARILib::errorLostRX),
    226, uint(MMVARILib::errorLostTX),
    227, uint(MMVARILib::errorSoundOpen),
    228, uint(MMVARILib::errorComOpen),
    230, uint(MMVARILib::pttlineRTS),
    231, uint(MMVARILib::pttlineDTR),
    232, uint(MMVARILib::pttlineTXD),
    234, uint(MMVARILib::cmdtxRX),
    235, uint(MMVARILib::cmdtxTX),
    236, uint(MMVARILib::cmdtxREQRX),
    237, uint(MMVARILib::cmdtxCW),
    238, uint(MMVARILib::cmdtxTONE),
    240, uint(MMVARILib::txstateRX),
    241, uint(MMVARILib::txstateTX),
    242, uint(MMVARILib::txstateREQRX),
    243, uint(MMVARILib::txstateWAIT),
    244, uint(MMVARILib::txstateTONE),
    246, uint(MMVARILib::viewtypeFFT),
    247, uint(MMVARILib::viewtypeWATER),
    248, uint(MMVARILib::viewtypeWAVE),
    249, uint(MMVARILib::viewtypeFREQERR),
    250, uint(MMVARILib::viewtypeSMALLWATER),
    0 // eod
};

XMMVBtn::XMMVBtn(QWidget *parent, Qt::WindowFlags f) :
    QAxWidget(parent, f)
{
    setControl(QStringLiteral("{0bdf39bd-46d0-42e8-b8b2-6045feac5f4f}"));
}

const QMetaObject XMMVBtn::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_MMVARILib__XMMVBtn, nullptr, nullptr, nullptr }
};

void *XMMVBtn::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "MMVARILib::XMMVBtn"))
        return static_cast<void*>(const_cast<XMMVBtn*>(this));
    return QAxWidget::qt_metacast(_clname);
}
static const uint qt_meta_data_MMVARILib___DXMMVLvl[] = {

 // content:
    7, // revision
    302,  // classname
    0, 0, // classinfo
    18, 14, // methods
    12, 172, // properties
    6, 208, // enums/sets
    0, 0, // constructors
    0, // flags
    4, // signal count

// signal: name, argc, parameters, tag, flags
    303, 1, 104, 2, 5,
    1, 4, 107, 2, 5,
    7, 1, 116, 2, 5,
    9, 3, 119, 2, 5,

// slot: name, argc, parameters, tag, flags
    305, 0, 126, 2, 9,
    306, 2, 127, 2, 9,
    307, 3, 132, 2, 9,
    311, 1, 139, 2, 9,
    313, 1, 142, 2, 9,
    314, 1, 145, 2, 9,
    316, 1, 148, 2, 9,
    318, 1, 151, 2, 9,
    320, 1, 154, 2, 9,
    322, 1, 157, 2, 9,
    324, 1, 160, 2, 9,
    326, 1, 163, 2, 9,
    296, 1, 166, 2, 9,
    135, 1, 169, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, 304,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 132, 41,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, 308, 309, 310,
    QMetaType::Void, QMetaType::QColor, 312,
    QMetaType::Void, QMetaType::Int, 304,
    QMetaType::Void, QMetaType::QColor, 315,
    QMetaType::Void, QMetaType::Int, 317,
    QMetaType::Void, QMetaType::QColor, 319,
    QMetaType::Void, QMetaType::QColor, 321,
    QMetaType::Void, QMetaType::QColor, 323,
    QMetaType::Void, QMetaType::QColor, 325,
    QMetaType::Void, QMetaType::QColor, 327,
    QMetaType::Void, QMetaType::Bool, 297,
    QMetaType::Void, QMetaType::Int, 136,

 // properties: name, type, flags
    312, QMetaType::QColor, 0x43015003, 		 // QColor BackColor
    304, QMetaType::Int, 0x02015003, 		 // int BorderStyle
    315, QMetaType::QColor, 0x43015003, 		 // QColor LineColor
    317, QMetaType::Int, 0x02015003, 		 // int MaxLevel
    319, QMetaType::QColor, 0x43015003, 		 // QColor OffColor
    321, QMetaType::QColor, 0x43015003, 		 // QColor OnColor
    323, QMetaType::QColor, 0x43015003, 		 // QColor OverColor
    325, QMetaType::QColor, 0x43015003, 		 // QColor TxColor
    327, QMetaType::QColor, 0x43015003, 		 // QColor UnlockColor
    297, QMetaType::Bool, 0x01015003, 		 // bool Visible
    218, QMetaType::QString, 0x0a055003, 		 // QString control
    136, QMetaType::Int, 0x02015003, 		 // int hWnd

 // enums: name, flags, count, data
    219, 0x0, 3, 232, 
    223, 0x0, 5, 238, 
    229, 0x0, 3, 248, 
    233, 0x0, 5, 254, 
    239, 0x0, 5, 264, 
    245, 0x0, 5, 274, 

 // enum data: key, value
    220, uint(MMVARILib::collectNONE),
    221, uint(MMVARILib::collectSYNC),
    222, uint(MMVARILib::collectWAVE),
    224, uint(MMVARILib::errorNONE),
    225, uint(MMVARILib::errorLostRX),
    226, uint(MMVARILib::errorLostTX),
    227, uint(MMVARILib::errorSoundOpen),
    228, uint(MMVARILib::errorComOpen),
    230, uint(MMVARILib::pttlineRTS),
    231, uint(MMVARILib::pttlineDTR),
    232, uint(MMVARILib::pttlineTXD),
    234, uint(MMVARILib::cmdtxRX),
    235, uint(MMVARILib::cmdtxTX),
    236, uint(MMVARILib::cmdtxREQRX),
    237, uint(MMVARILib::cmdtxCW),
    238, uint(MMVARILib::cmdtxTONE),
    240, uint(MMVARILib::txstateRX),
    241, uint(MMVARILib::txstateTX),
    242, uint(MMVARILib::txstateREQRX),
    243, uint(MMVARILib::txstateWAIT),
    244, uint(MMVARILib::txstateTONE),
    246, uint(MMVARILib::viewtypeFFT),
    247, uint(MMVARILib::viewtypeWATER),
    248, uint(MMVARILib::viewtypeWAVE),
    249, uint(MMVARILib::viewtypeFREQERR),
    250, uint(MMVARILib::viewtypeSMALLWATER),
    0 // eod
};

_DXMMVLvl::_DXMMVLvl(IDispatch *subobject, QAxObject *parent) :
    QAxObject(subobject, parent)
{
    internalRelease();
}

const QMetaObject _DXMMVLvl::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_MMVARILib___DXMMVLvl, nullptr, nullptr, nullptr }
};

void *_DXMMVLvl::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "MMVARILib::_DXMMVLvl"))
        return static_cast<void*>(const_cast<_DXMMVLvl*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_MMVARILib__XMMVLvl[] = {

 // content:
    7, // revision
    328,  // classname
    1, 14, // classinfo
    24, 16, // methods
    11, 222, // properties
    6, 255, // enums/sets
    0, 0, // constructors
    0, // flags
    10, // signal count

 // classinfo: key, value
    252, 329, 

// signal: name, argc, parameters, tag, flags
    303, 1, 136, 2, 5,
    330, 1, 139, 2, 5,
    332, 1, 142, 2, 5,
    333, 1, 145, 2, 5,
    334, 1, 148, 2, 5,
    335, 1, 151, 2, 5,
    336, 1, 154, 2, 5,
    1, 4, 157, 2, 5,
    7, 1, 166, 2, 5,
    9, 3, 169, 2, 5,

// slot: name, argc, parameters, tag, flags
    305, 0, 176, 2, 9,
    306, 2, 177, 2, 9,
    307, 3, 182, 2, 9,
    311, 1, 189, 2, 9,
    313, 1, 192, 2, 9,
    314, 1, 195, 2, 9,
    316, 1, 198, 2, 9,
    318, 1, 201, 2, 9,
    320, 1, 204, 2, 9,
    322, 1, 207, 2, 9,
    324, 1, 210, 2, 9,
    326, 1, 213, 2, 9,
    296, 1, 216, 2, 9,
    135, 1, 219, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, 304,
    QMetaType::Void, QMetaType::Int, 331,
    QMetaType::Void, QMetaType::Int, 331,
    QMetaType::Void, QMetaType::Int, 331,
    QMetaType::Void, QMetaType::Int, 331,
    QMetaType::Void, QMetaType::Int, 331,
    QMetaType::Void, QMetaType::Int, 331,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 132, 41,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, 308, 309, 310,
    QMetaType::Void, QMetaType::QColor, 312,
    QMetaType::Void, QMetaType::Int, 304,
    QMetaType::Void, QMetaType::QColor, 315,
    QMetaType::Void, QMetaType::Int, 317,
    QMetaType::Void, QMetaType::QColor, 319,
    QMetaType::Void, QMetaType::QColor, 321,
    QMetaType::Void, QMetaType::QColor, 323,
    QMetaType::Void, QMetaType::QColor, 325,
    QMetaType::Void, QMetaType::QColor, 327,
    QMetaType::Void, QMetaType::Bool, 297,
    QMetaType::Void, QMetaType::Int, 136,

 // properties: name, type, flags
    312, QMetaType::QColor, 0x43015003, 		 // QColor BackColor
    304, QMetaType::Int, 0x02015003, 		 // int BorderStyle
    315, QMetaType::QColor, 0x43015003, 		 // QColor LineColor
    317, QMetaType::Int, 0x02015003, 		 // int MaxLevel
    319, QMetaType::QColor, 0x43015003, 		 // QColor OffColor
    321, QMetaType::QColor, 0x43015003, 		 // QColor OnColor
    323, QMetaType::QColor, 0x43015003, 		 // QColor OverColor
    325, QMetaType::QColor, 0x43015003, 		 // QColor TxColor
    327, QMetaType::QColor, 0x43015003, 		 // QColor UnlockColor
    297, QMetaType::Bool, 0x01015003, 		 // bool Visible
    136, QMetaType::Int, 0x02015003, 		 // int hWnd

 // enums: name, flags, count, data
    219, 0x0, 3, 279, 
    223, 0x0, 5, 285, 
    229, 0x0, 3, 295, 
    233, 0x0, 5, 301, 
    239, 0x0, 5, 311, 
    245, 0x0, 5, 321, 

 // enum data: key, value
    220, uint(MMVARILib::collectNONE),
    221, uint(MMVARILib::collectSYNC),
    222, uint(MMVARILib::collectWAVE),
    224, uint(MMVARILib::errorNONE),
    225, uint(MMVARILib::errorLostRX),
    226, uint(MMVARILib::errorLostTX),
    227, uint(MMVARILib::errorSoundOpen),
    228, uint(MMVARILib::errorComOpen),
    230, uint(MMVARILib::pttlineRTS),
    231, uint(MMVARILib::pttlineDTR),
    232, uint(MMVARILib::pttlineTXD),
    234, uint(MMVARILib::cmdtxRX),
    235, uint(MMVARILib::cmdtxTX),
    236, uint(MMVARILib::cmdtxREQRX),
    237, uint(MMVARILib::cmdtxCW),
    238, uint(MMVARILib::cmdtxTONE),
    240, uint(MMVARILib::txstateRX),
    241, uint(MMVARILib::txstateTX),
    242, uint(MMVARILib::txstateREQRX),
    243, uint(MMVARILib::txstateWAIT),
    244, uint(MMVARILib::txstateTONE),
    246, uint(MMVARILib::viewtypeFFT),
    247, uint(MMVARILib::viewtypeWATER),
    248, uint(MMVARILib::viewtypeWAVE),
    249, uint(MMVARILib::viewtypeFREQERR),
    250, uint(MMVARILib::viewtypeSMALLWATER),
    0 // eod
};

XMMVLvl::XMMVLvl(QWidget *parent, Qt::WindowFlags f) :
    QAxWidget(parent, f)
{
    setControl(QStringLiteral("{438ef93a-939d-4b6b-93a7-df09049b8514}"));
}

const QMetaObject XMMVLvl::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_MMVARILib__XMMVLvl, nullptr, nullptr, nullptr }
};

void *XMMVLvl::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "MMVARILib::XMMVLvl"))
        return static_cast<void*>(const_cast<XMMVLvl*>(this));
    return QAxWidget::qt_metacast(_clname);
}
static const uint qt_meta_data_MMVARILib___DXMMVView[] = {

 // content:
    7, // revision
    337,  // classname
    0, 0, // classinfo
    55, 14, // methods
    27, 482, // properties
    6, 563, // enums/sets
    0, 0, // constructors
    0, // flags
    5, // signal count

// signal: name, argc, parameters, tag, flags
    303, 1, 289, 2, 5,
    280, 1, 292, 2, 5,
    1, 4, 295, 2, 5,
    7, 1, 304, 2, 5,
    9, 3, 307, 2, 5,

// slot: name, argc, parameters, tag, flags
    338, 0, 314, 2, 9,
    339, 1, 315, 2, 9,
    340, 1, 318, 2, 9,
    341, 1, 321, 2, 9,
    342, 1, 324, 2, 9,
    306, 1, 327, 2, 9,
    343, 2, 330, 2, 9,
    344, 2, 335, 2, 9,
    345, 1, 340, 2, 9,
    346, 0, 343, 2, 9,
    313, 1, 344, 2, 9,
    347, 2, 347, 2, 9,
    348, 2, 352, 2, 9,
    349, 2, 357, 2, 9,
    350, 2, 362, 2, 9,
    289, 1, 367, 2, 9,
    296, 1, 370, 2, 9,
    351, 2, 373, 2, 9,
    352, 1, 378, 2, 9,
    353, 1, 381, 2, 9,
    355, 1, 384, 2, 9,
    357, 1, 387, 2, 9,
    359, 1, 390, 2, 9,
    361, 1, 393, 2, 9,
    363, 1, 396, 2, 9,
    365, 1, 399, 2, 9,
    367, 1, 402, 2, 9,
    369, 1, 405, 2, 9,
    371, 1, 408, 2, 9,
    373, 1, 411, 2, 9,
    135, 1, 414, 2, 9,
    375, 2, 417, 2, 9,
    376, 2, 422, 2, 9,
    377, 2, 427, 2, 9,
    378, 1, 432, 2, 9,
    380, 1, 435, 2, 9,
    382, 1, 438, 2, 9,
    384, 1, 441, 2, 9,
    386, 1, 444, 2, 9,
    388, 1, 447, 2, 9,
    390, 1, 450, 2, 9,
    392, 2, 453, 2, 9,
    393, 1, 458, 2, 9,
    395, 1, 461, 2, 9,
    397, 1, 464, 2, 9,
    399, 1, 467, 2, 9,
    401, 1, 470, 2, 9,
    402, 1, 473, 2, 9,
    403, 1, 476, 2, 9,
    404, 1, 479, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, 304,
    QMetaType::Void, 0x80000000 | 281, 282,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::QColor, QMetaType::Int, 41,
    QMetaType::QColor, QMetaType::Int, 41,
    QMetaType::QColor, QMetaType::Int, 41,
    QMetaType::QColor, QMetaType::Int, 41,
    QMetaType::Void, QMetaType::Int, 132,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 132, 41,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 132, 41,
    QMetaType::Void, QMetaType::Int, 132,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 304,
    QMetaType::Void, QMetaType::Int, QMetaType::QColor, 41, 77,
    QMetaType::Void, QMetaType::Int, QMetaType::QColor, 41, 77,
    QMetaType::Void, QMetaType::Int, QMetaType::QColor, 41, 77,
    QMetaType::Void, QMetaType::Int, QMetaType::QColor, 41, 77,
    QMetaType::Void, 0x80000000 | 281, 282,
    QMetaType::Void, QMetaType::Bool, 297,
    QMetaType::Void, QMetaType::Int, QMetaType::QColor, 41, 77,
    QMetaType::QColor, QMetaType::Int, 41,
    QMetaType::Void, QMetaType::Bool, 354,
    QMetaType::Void, QMetaType::Bool, 356,
    QMetaType::Void, QMetaType::Bool, 358,
    QMetaType::Void, QMetaType::Bool, 360,
    QMetaType::Void, QMetaType::Bool, 362,
    QMetaType::Void, QMetaType::Bool, 364,
    QMetaType::Void, QMetaType::Bool, 366,
    QMetaType::Void, QMetaType::Bool, 368,
    QMetaType::Void, QMetaType::Bool, 370,
    QMetaType::Void, QMetaType::Bool, 372,
    QMetaType::Void, QMetaType::Int, 374,
    QMetaType::Void, QMetaType::Int, 136,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, 41, 77,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, 41, 77,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, 41, 77,
    QMetaType::Void, QMetaType::Int, 379,
    QMetaType::Void, QMetaType::Int, 381,
    QMetaType::Void, QMetaType::Int, 383,
    QMetaType::Void, QMetaType::Int, 385,
    QMetaType::Void, QMetaType::Int, 387,
    QMetaType::Void, QMetaType::Int, 389,
    QMetaType::Void, QMetaType::Int, 391,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 41, 77,
    QMetaType::Void, QMetaType::Int, 394,
    QMetaType::Void, QMetaType::Int, 396,
    QMetaType::Void, QMetaType::Int, 398,
    QMetaType::Void, QMetaType::Int, 400,
    QMetaType::QString, QMetaType::Int, 41,
    QMetaType::QString, QMetaType::Int, 41,
    QMetaType::QString, QMetaType::Int, 41,
    QMetaType::Int, QMetaType::Int, 41,

 // properties: name, type, flags
    304, QMetaType::Int, 0x02015003, 		 // int BorderStyle
    282, 0x80000000 | 281, 0x00015003, 		 // stdole::Font* Font
    297, QMetaType::Bool, 0x01015003, 		 // bool Visible
    354, QMetaType::Bool, 0x01015003, 		 // bool bAttachMouse
    356, QMetaType::Bool, 0x01015003, 		 // bool bFollowRxFreq
    358, QMetaType::Bool, 0x01015003, 		 // bool bHighQuality
    360, QMetaType::Bool, 0x01015003, 		 // bool bLSB
    362, QMetaType::Bool, 0x01015003, 		 // bool bShowErrorMsg
    364, QMetaType::Bool, 0x01015003, 		 // bool bShowNotchMarkers
    366, QMetaType::Bool, 0x01015003, 		 // bool bShowSubChannelMarkers
    368, QMetaType::Bool, 0x01015003, 		 // bool bShowSync
    370, QMetaType::Bool, 0x01015003, 		 // bool bWaterAGC
    372, QMetaType::Bool, 0x01015003, 		 // bool bWindowsMouseEvent
    218, QMetaType::QString, 0x0a055003, 		 // QString control
    374, QMetaType::Int, 0x02015003, 		 // int dwFreqHz
    136, QMetaType::Int, 0x02015003, 		 // int hWnd
    379, QMetaType::Int, 0x02015003, 		 // int wBaseFreq
    381, QMetaType::Int, 0x02015003, 		 // int wCursorFreq
    383, QMetaType::Int, 0x02015003, 		 // int wMouseChannel
    385, QMetaType::Int, 0x02015003, 		 // int wMouseNotch
    387, QMetaType::Int, 0x02015003, 		 // int wPixelXW
    389, QMetaType::Int, 0x02015003, 		 // int wPixelYW
    391, QMetaType::Int, 0x02015003, 		 // int wType
    394, QMetaType::Int, 0x02015003, 		 // int wWaterNoise
    396, QMetaType::Int, 0x02015003, 		 // int wWaterNoiseH
    398, QMetaType::Int, 0x02015003, 		 // int wWaterNoiseL
    400, QMetaType::Int, 0x02015003, 		 // int wWidthFreq

 // enums: name, flags, count, data
    219, 0x0, 3, 587, 
    223, 0x0, 5, 593, 
    229, 0x0, 3, 603, 
    233, 0x0, 5, 609, 
    239, 0x0, 5, 619, 
    245, 0x0, 5, 629, 

 // enum data: key, value
    220, uint(MMVARILib::collectNONE),
    221, uint(MMVARILib::collectSYNC),
    222, uint(MMVARILib::collectWAVE),
    224, uint(MMVARILib::errorNONE),
    225, uint(MMVARILib::errorLostRX),
    226, uint(MMVARILib::errorLostTX),
    227, uint(MMVARILib::errorSoundOpen),
    228, uint(MMVARILib::errorComOpen),
    230, uint(MMVARILib::pttlineRTS),
    231, uint(MMVARILib::pttlineDTR),
    232, uint(MMVARILib::pttlineTXD),
    234, uint(MMVARILib::cmdtxRX),
    235, uint(MMVARILib::cmdtxTX),
    236, uint(MMVARILib::cmdtxREQRX),
    237, uint(MMVARILib::cmdtxCW),
    238, uint(MMVARILib::cmdtxTONE),
    240, uint(MMVARILib::txstateRX),
    241, uint(MMVARILib::txstateTX),
    242, uint(MMVARILib::txstateREQRX),
    243, uint(MMVARILib::txstateWAIT),
    244, uint(MMVARILib::txstateTONE),
    246, uint(MMVARILib::viewtypeFFT),
    247, uint(MMVARILib::viewtypeWATER),
    248, uint(MMVARILib::viewtypeWAVE),
    249, uint(MMVARILib::viewtypeFREQERR),
    250, uint(MMVARILib::viewtypeSMALLWATER),
    0 // eod
};

_DXMMVView::_DXMMVView(IDispatch *subobject, QAxObject *parent) :
    QAxObject(subobject, parent)
{
    internalRelease();
}

const QMetaObject _DXMMVView::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_MMVARILib___DXMMVView, nullptr, nullptr, nullptr }
};

void *_DXMMVView::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "MMVARILib::_DXMMVView"))
        return static_cast<void*>(const_cast<_DXMMVView*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_MMVARILib__XMMVView[] = {

 // content:
    7, // revision
    405,  // classname
    1, 14, // classinfo
    67, 16, // methods
    26, 594, // properties
    6, 672, // enums/sets
    0, 0, // constructors
    0, // flags
    17, // signal count

 // classinfo: key, value
    252, 406, 

// signal: name, argc, parameters, tag, flags
    303, 1, 351, 2, 5,
    280, 1, 354, 2, 5,
    330, 1, 357, 2, 5,
    332, 1, 360, 2, 5,
    333, 1, 363, 2, 5,
    334, 1, 366, 2, 5,
    335, 1, 369, 2, 5,
    336, 1, 372, 2, 5,
    407, 2, 375, 2, 5,
    410, 2, 380, 2, 5,
    411, 2, 385, 2, 5,
    412, 3, 390, 2, 5,
    414, 2, 397, 2, 5,
    415, 2, 402, 2, 5,
    1, 4, 407, 2, 5,
    7, 1, 416, 2, 5,
    9, 3, 419, 2, 5,

// slot: name, argc, parameters, tag, flags
    338, 0, 426, 2, 9,
    339, 1, 427, 2, 9,
    340, 1, 430, 2, 9,
    341, 1, 433, 2, 9,
    342, 1, 436, 2, 9,
    306, 1, 439, 2, 9,
    343, 2, 442, 2, 9,
    344, 2, 447, 2, 9,
    345, 1, 452, 2, 9,
    346, 0, 455, 2, 9,
    313, 1, 456, 2, 9,
    347, 2, 459, 2, 9,
    348, 2, 464, 2, 9,
    349, 2, 469, 2, 9,
    350, 2, 474, 2, 9,
    289, 1, 479, 2, 9,
    296, 1, 482, 2, 9,
    351, 2, 485, 2, 9,
    352, 1, 490, 2, 9,
    353, 1, 493, 2, 9,
    355, 1, 496, 2, 9,
    357, 1, 499, 2, 9,
    359, 1, 502, 2, 9,
    361, 1, 505, 2, 9,
    363, 1, 508, 2, 9,
    365, 1, 511, 2, 9,
    367, 1, 514, 2, 9,
    369, 1, 517, 2, 9,
    371, 1, 520, 2, 9,
    373, 1, 523, 2, 9,
    135, 1, 526, 2, 9,
    375, 2, 529, 2, 9,
    376, 2, 534, 2, 9,
    377, 2, 539, 2, 9,
    378, 1, 544, 2, 9,
    380, 1, 547, 2, 9,
    382, 1, 550, 2, 9,
    384, 1, 553, 2, 9,
    386, 1, 556, 2, 9,
    388, 1, 559, 2, 9,
    390, 1, 562, 2, 9,
    392, 2, 565, 2, 9,
    393, 1, 570, 2, 9,
    395, 1, 573, 2, 9,
    397, 1, 576, 2, 9,
    399, 1, 579, 2, 9,
    401, 1, 582, 2, 9,
    402, 1, 585, 2, 9,
    403, 1, 588, 2, 9,
    404, 1, 591, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, 304,
    QMetaType::Void, 0x80000000 | 281, 282,
    QMetaType::Void, QMetaType::Int, 14,
    QMetaType::Void, QMetaType::Int, 14,
    QMetaType::Void, QMetaType::Int, 14,
    QMetaType::Void, QMetaType::Int, 14,
    QMetaType::Void, QMetaType::Int, 14,
    QMetaType::Void, QMetaType::Int, 14,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 408, 409,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 408, 409,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 408, 409,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, 413, 408, 409,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 408, 409,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 408, 409,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::QColor, QMetaType::Int, 41,
    QMetaType::QColor, QMetaType::Int, 41,
    QMetaType::QColor, QMetaType::Int, 41,
    QMetaType::QColor, QMetaType::Int, 41,
    QMetaType::Void, QMetaType::Int, 132,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 132, 41,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 132, 41,
    QMetaType::Void, QMetaType::Int, 132,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 304,
    QMetaType::Void, QMetaType::Int, QMetaType::QColor, 41, 77,
    QMetaType::Void, QMetaType::Int, QMetaType::QColor, 41, 77,
    QMetaType::Void, QMetaType::Int, QMetaType::QColor, 41, 77,
    QMetaType::Void, QMetaType::Int, QMetaType::QColor, 41, 77,
    QMetaType::Void, 0x80000000 | 281, 282,
    QMetaType::Void, QMetaType::Bool, 297,
    QMetaType::Void, QMetaType::Int, QMetaType::QColor, 41, 77,
    QMetaType::QColor, QMetaType::Int, 41,
    QMetaType::Void, QMetaType::Bool, 354,
    QMetaType::Void, QMetaType::Bool, 356,
    QMetaType::Void, QMetaType::Bool, 358,
    QMetaType::Void, QMetaType::Bool, 360,
    QMetaType::Void, QMetaType::Bool, 362,
    QMetaType::Void, QMetaType::Bool, 364,
    QMetaType::Void, QMetaType::Bool, 366,
    QMetaType::Void, QMetaType::Bool, 368,
    QMetaType::Void, QMetaType::Bool, 370,
    QMetaType::Void, QMetaType::Bool, 372,
    QMetaType::Void, QMetaType::Int, 374,
    QMetaType::Void, QMetaType::Int, 136,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, 41, 77,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, 41, 77,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, 41, 77,
    QMetaType::Void, QMetaType::Int, 379,
    QMetaType::Void, QMetaType::Int, 381,
    QMetaType::Void, QMetaType::Int, 383,
    QMetaType::Void, QMetaType::Int, 385,
    QMetaType::Void, QMetaType::Int, 387,
    QMetaType::Void, QMetaType::Int, 389,
    QMetaType::Void, QMetaType::Int, 391,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 41, 77,
    QMetaType::Void, QMetaType::Int, 394,
    QMetaType::Void, QMetaType::Int, 396,
    QMetaType::Void, QMetaType::Int, 398,
    QMetaType::Void, QMetaType::Int, 400,
    QMetaType::QString, QMetaType::Int, 41,
    QMetaType::QString, QMetaType::Int, 41,
    QMetaType::QString, QMetaType::Int, 41,
    QMetaType::Int, QMetaType::Int, 41,

 // properties: name, type, flags
    304, QMetaType::Int, 0x02015003, 		 // int BorderStyle
    282, 0x80000000 | 281, 0x00015003, 		 // stdole::Font* Font
    297, QMetaType::Bool, 0x01015003, 		 // bool Visible
    354, QMetaType::Bool, 0x01015003, 		 // bool bAttachMouse
    356, QMetaType::Bool, 0x01015003, 		 // bool bFollowRxFreq
    358, QMetaType::Bool, 0x01015003, 		 // bool bHighQuality
    360, QMetaType::Bool, 0x01015003, 		 // bool bLSB
    362, QMetaType::Bool, 0x01015003, 		 // bool bShowErrorMsg
    364, QMetaType::Bool, 0x01015003, 		 // bool bShowNotchMarkers
    366, QMetaType::Bool, 0x01015003, 		 // bool bShowSubChannelMarkers
    368, QMetaType::Bool, 0x01015003, 		 // bool bShowSync
    370, QMetaType::Bool, 0x01015003, 		 // bool bWaterAGC
    372, QMetaType::Bool, 0x01015003, 		 // bool bWindowsMouseEvent
    374, QMetaType::Int, 0x02015003, 		 // int dwFreqHz
    136, QMetaType::Int, 0x02015003, 		 // int hWnd
    379, QMetaType::Int, 0x02015003, 		 // int wBaseFreq
    381, QMetaType::Int, 0x02015003, 		 // int wCursorFreq
    383, QMetaType::Int, 0x02015003, 		 // int wMouseChannel
    385, QMetaType::Int, 0x02015003, 		 // int wMouseNotch
    387, QMetaType::Int, 0x02015003, 		 // int wPixelXW
    389, QMetaType::Int, 0x02015003, 		 // int wPixelYW
    391, QMetaType::Int, 0x02015003, 		 // int wType
    394, QMetaType::Int, 0x02015003, 		 // int wWaterNoise
    396, QMetaType::Int, 0x02015003, 		 // int wWaterNoiseH
    398, QMetaType::Int, 0x02015003, 		 // int wWaterNoiseL
    400, QMetaType::Int, 0x02015003, 		 // int wWidthFreq

 // enums: name, flags, count, data
    219, 0x0, 3, 696, 
    223, 0x0, 5, 702, 
    229, 0x0, 3, 712, 
    233, 0x0, 5, 718, 
    239, 0x0, 5, 728, 
    245, 0x0, 5, 738, 

 // enum data: key, value
    220, uint(MMVARILib::collectNONE),
    221, uint(MMVARILib::collectSYNC),
    222, uint(MMVARILib::collectWAVE),
    224, uint(MMVARILib::errorNONE),
    225, uint(MMVARILib::errorLostRX),
    226, uint(MMVARILib::errorLostTX),
    227, uint(MMVARILib::errorSoundOpen),
    228, uint(MMVARILib::errorComOpen),
    230, uint(MMVARILib::pttlineRTS),
    231, uint(MMVARILib::pttlineDTR),
    232, uint(MMVARILib::pttlineTXD),
    234, uint(MMVARILib::cmdtxRX),
    235, uint(MMVARILib::cmdtxTX),
    236, uint(MMVARILib::cmdtxREQRX),
    237, uint(MMVARILib::cmdtxCW),
    238, uint(MMVARILib::cmdtxTONE),
    240, uint(MMVARILib::txstateRX),
    241, uint(MMVARILib::txstateTX),
    242, uint(MMVARILib::txstateREQRX),
    243, uint(MMVARILib::txstateWAIT),
    244, uint(MMVARILib::txstateTONE),
    246, uint(MMVARILib::viewtypeFFT),
    247, uint(MMVARILib::viewtypeWATER),
    248, uint(MMVARILib::viewtypeWAVE),
    249, uint(MMVARILib::viewtypeFREQERR),
    250, uint(MMVARILib::viewtypeSMALLWATER),
    0 // eod
};

XMMVView::XMMVView(QWidget *parent, Qt::WindowFlags f) :
    QAxWidget(parent, f)
{
    setControl(QStringLiteral("{702cbf07-c159-44f2-b8a6-df8ea1001e08}"));
}

const QMetaObject XMMVView::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_MMVARILib__XMMVView, nullptr, nullptr, nullptr }
};

void *XMMVView::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "MMVARILib::XMMVView"))
        return static_cast<void*>(const_cast<XMMVView*>(this));
    return QAxWidget::qt_metacast(_clname);
}

