######################################################################
# Automatically generated by qmake (2.01a) Fr Mai 25 19:04:58 2007
######################################################################

include("maia/maia.pri")

TEMPLATE = lib #app
TARGET = maia
CONFIG += staticlib

DEPENDPATH += .
INCLUDEPATH += .
QT -= gui
CONFIG += qt silent #debug

macx {
    QMAKE_MACOSX_DEPLOYMENT_TARGET = 10.15
    QMAKE_TARGET_BUNDLE_PREFIX = uk.org.g0gjv.minos
    MY_ENTITLEMENTS.name = CODE_SIGN_ENTITLEMENTS
    MY_ENTITLEMENTS.value = ../ControlFiles/minos.entitlements
    QMAKE_MAC_XCODE_SETTINGS += MY_ENTITLEMENTS

#    QMAKE_APPLE_DEVICE_ARCHS = x86_64 arm64
    QMAKE_APPLE_DEVICE_ARCHS = x86_64
}

target.path = $$PREFIX/lib

headers.files = \
    maia/maiaFault.h \
    maia/maiaObject.h \
    maia/maiaXmlRpcClient.h \
    maia/maiaXmlRpcServer.h \
    maia/maiaXmlRpcServerConnection.h \

headers.path = $$PREFIX/include/maia

INSTALLS += \
    target \
    headers \

# Input

