######################################################################
# Automatically generated by qmake (2.01a) Fr Mai 25 19:04:58 2007
######################################################################

include($$PWD/../mqt.pri)

TEMPLATE = lib
TARGET = maia
CONFIG += staticlib

INCLUDEPATH += $$PWD/
QT -= gui
QT += xml network

HEADERS += maiaObject.h \
            maiaFault.h \
            maiaXmlRpcClient.h \
            maiaXmlRpcServer.h \
            maiaXmlRpcServerConnection.h

SOURCES += maiaObject.cpp \
           maiaFault.cpp \
           maiaXmlRpcClient.cpp \
           maiaXmlRpcServer.cpp \
           maiaXmlRpcServerConnection.cpp
