[None]
Path=
Enabled=true
Requires=
Server=false
HideApp = true

[AppStarter]
Path=./Bin/MqtAppStarter.app
Enabled=false
Requires=
Server=false

[BandMap]
Path=./Bin/MqtBandMap.app
Enabled=false
Requires=Server
Server=false

[Chat]
Path=./Bin/MqtChat.app
Enabled=true
Requires=Server
Server=false
Where=local

[Cluster]
Path=./Bin/MqtCluster.app
Enabled=true
Requires=Server
Server=false

[DataModes]
Path=./Bin/MqtDataModes.app
Enabled=true
Requires=Server
Server=false

[Keyer]
Path=./Bin/MqtKeyer.app
Enabled=true
Requires=Server
Server=false
Where=remote

[KeyerProxy]
Path=./Bin/MqtKeyerProxy.app
Enabled=true
Requires=Server
Server=false
#Where=remote
   
[KSTClient]
Path=./Bin/MqtKSTClient.app
Enabled=true
Requires=Server
Server=false

[LineControl]
Path=./Bin/MqtControl.app
Enabled=false
Requires=
Server=true
HideApp = true

[Logger]
Path=./Bin/MqtLogger.app
Enabled=false
Requires=
Server=false

[Monitor]
Path=./Bin/MqtMonitor.app
Enabled=true
Requires=Server
Server=false
Where=local

[Other]
Path=
Enabled=false
Requires=
Server=false

[RigControl]
Path=./Bin/MqtRigControl.app
Enabled=true
Requires=Server
Server=true

[RigRecorder]
Path=./Bin/MqtRigRecorder.app
Enabled=true
Requires=Server
Server=false

[RigSync]
Path=./Bin/MqtRigSync.app
Enabled=true
Requires=Server
Server=false

[Rotator]
Path=./Bin/MqtRotator.app
Enabled=true
Requires=Server
Server=true

[QrzServer]
Path=./Bin/MqtQrzServer.app
Enabled=true
Requires=Server
Server=true

[Server]
Path=./Bin/MqtServer.app
Enabled=true
Requires=
Server=true
HideApp = true
Where=local
