#!/usr/bin/env bash
# Turns $STAGE into a pacman package (.pkg.tar.zst) in $OUTDIR.
set -euo pipefail
HERE="$(dirname "$(readlink -f "$0")")"
. "$HERE/target.sh"

STAGE="${STAGE:?}"; OUTDIR="${OUTDIR:?}"; VERSION="${MINOS_VERSION:?}"
REL="${PKG_RELEASE:-1}"
mkdir -p "$OUTDIR"

# pacman versions may not contain a hyphen; the upstream scheme never does,
# but normalise anyway so an odd tag cannot break the build.
PKGVER="${VERSION//-/_}"

# makepkg refuses to run as root.
id -u builder >/dev/null 2>&1 || useradd -m builder
WORK="$(mktemp -d)"
chmod 0755 "$WORK"

DEPENDS="'qt6-base' 'qt6-serialport' 'qt6-charts' 'qt6-multimedia' 'qt6-translations' 'alsa-lib'"
if [ "${MINOS_HAMLIB_BUNDLED:-0}" = "1" ]; then
    # makepkg does not derive dependencies from ELF files, so the bundled
    # Hamlib's own needs have to be named here.
    DEPENDS="$DEPENDS 'libusb'"
else
    DEPENDS="$DEPENDS 'hamlib'"
fi

cat > "$WORK/PKGBUILD" <<EOF
# Generated by the Minos2-Mirror CI. The tree is already built and staged;
# package() only installs it.
pkgname=$MINOS_PKGNAME
pkgver=$PKGVER
pkgrel=$REL
pkgdesc="Minos amateur radio contest logger (${MINOS_REF:-Minos2 sources})"
arch=('$(uname -m)')
url="https://sourceforge.net/projects/minos/"
license=('GPL-3.0-or-later')
depends=($DEPENDS)
options=('!strip' '!debug' '!lto')

package() {
    cp -a "$STAGE"/. "\$pkgdir"/
}
EOF

chown -R builder "$WORK"
# The staged tree must be readable by the build user.
chmod -R a+rX "$STAGE"
( cd "$WORK" && sudo -u builder makepkg --nodeps --noextract --noconfirm )

find "$WORK" -name '*.pkg.tar.zst' -exec cp -v {} "$OUTDIR/" \;
rm -rf "$WORK"

for f in "$OUTDIR"/*.pkg.tar.zst; do
    echo "==> $f"
    pacman -Qip "$f"
done
