# Note! The escape character is used eg \' \" \\
[AllRadios]
messageStoredInRadio=false
maxMsgLength=24
supportedCharacters="ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 /?"
supportedCharRegEx="[A-Z0-9 \/\\?]+"



[Kenwood]
messageStoredInRadio=false
maxMsgLength=24
supportedCharacters="ABCDEFGHIJKLMNOPQRTUVWXYZ0123456789 \'\"()*+,-./:=?@"
supportedCharRegEx="[A-Z0-9 \'\"()*+,-./:=?@^]+"
radiosSupportSpecialChars="TS990S,TS890S,TS480"
specialCharacters="BT=[,SK=>,AR=_,KN=],AS=<,BK=\\,HH=#,SN=%"

[Elecraft]
messageStoredInRadio=false
maxMsgLength=24
supportedCharacters="ABCDEFGHIJKLMNOPQRTUVWXYZ0123456789 \'\"(),-./:=?@"
supportedCharRegEx="[A-Z0-9 \'\"(),-./:=?@^]+"
radiosSupportSpecialChars="K3,K3S,KX3,KX2,K4"
specialCharacters="AR=+,KN=(,BT==,AS=%,SK=*,VE=!"

[Icom]
messageStoredInRadio=false
maxMsgLength=24
supportedCharacters="ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 /?,.@"
supportedCharRegEx="[A-Z0-9 \/\\?,.@]+"
radiosSupportSpecialChars=""


[Yaesu]
messageStoredInRadio=false
maxMsgLength=50
messageEndChar="}"
supportedCharacters="ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 /?#*@"
supportedCharRegEx="[A-Z0-9 \/\\?#*@]+"
radiosSupportSpecialChars="FT991,FT891,FTDX10,Ft710,FTDX101"
radiosSupportSpecialChars="SN=!,AF=\",SX=$,KA=%,AS=&,WG=\',KN=(,KK=),AR=+,DN=/,KR=;BT=="

