# Note! The escape character is used eg \' \" \\
# NOTE! Curly brackets {} added to supportedCharacters to allow macro text
[AllRadios]
messageStoredInRadio=false
maxMsgLength=24
supportedCharacters="ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 /?{}"




[Kenwood]
messageStoredInRadio=false
maxMsgLength=24
supportedCharacters="ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 \'\"()*+,-./:=?@{}"
radiosSupportSpecialChars="TS990S,TS890S,TS480"
specialCharacters="BT=[,SK=>,AR=_,KN=],AS=<,BK=\\,HH=#,SN=%"

[Elecraft]
messageStoredInRadio=false
maxMsgLength=24
supportedCharacters="ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 \'\"(),-./:=?@{}"
radiosSupportSpecialChars="K3,K3S,KX3,KX2,K4"
specialCharacters="AR=+,KN=(,BT==,AS=%,SK=*,VE=!"

[Icom]
messageStoredInRadio=false
maxMsgLength=24
supportedCharacters="ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 /?,.@{}"
radiosSupportSpecialChars="IC7300,IC9700,IC705,IC905,IC7800,IC7700,IC7600,IC7410,IC7100,IC7610"
specialCharacters="BT= ,SK= ,AR= ,KN= ,AS= ,BK= ,HH= ,SN= "


[Yaesu]
messageStoredInRadio=false
maxMsgLength=50
supportedCharacters="ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 /?#*@"
radiosSupportSpecialChars="FT991,FT891,FTDX10,Ft710,FTDX101"
specialCharacters="SN=!,AF=\",SX=$,KA=%,AS=&,WG=\',KN=(,KK=),AR=+,DN=/,KR=;,BT=="

[Flex-radio]
messageStoredInRadio=false;
maxMsgLength=60
supportedCharacters="ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 .,?/=-+;"

[OpenHPSDR]
messageStoredInRadio=false;
maxMsgLength=60
supportedCharacters="ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 .,?/=-+;"

[Flex-radio/Apache]
messageStoredInRadio=false;
maxMsgLength=60
supportedCharacters="ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 .,?/=-+;"

[QRPLabs]
messageStoredInRadio=false;
maxMsgLength=60
supportedCharacters="ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 .,?/=-+;"

[Thetis]
messageStoredInRadio=false;
maxMsgLength=60
supportedCharacters="ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 .,?/=-+;"

