# These are the settings when using PC CWKEYER
# Note! The escape character is used eg \' \" \\
# NOTE! Macro characters now stored as their own string
[AllRadios]

maxMsgLength=90

supportedCharacters="ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789\\ /?"
macroCharacters="{}*#!%$"
messageStoredInRadio=false












